actions – SWAT+
actions Subroutine
812 statements
Source File
subroutine actions(ob_cur, ob_num, idtbl)
Uses
landuse_data_module
tillage_data_module
calibration_data_module
maximum_data_module
constituent_mass_module
climate_module
sd_channel_module
time_module
reservoir_data_module
tiles_data_module
basin_module
output_landscape_module
conditional_module
plant_data_module
hru_lte_module
hydrograph_module
organic_mineral_mass_module
fertilizer_data_module
water_allocation_module
septic_data_module
plant_module
mgt_operations_module
aquifer_module
soil_module
water_body_module
manure_allocation_module
hru_module
reservoir_module
if unlimited source, set irrigation applied directly to hru set demand for irrigation from channel, reservoir or aquifer check number of applications per year check for generic plant-harv and set crops check to see if the crop is already growing don't plant if the crop is already growing check for generic plant-harv and set crops sum yield and num. of harvest to calc ave yields sum basin crop yields and area harvested sum regional crop yields for soft calibration check for generic plant-harv and set crops sum yield and number of harvests to calc ave yields sum basin crop yields and area harvested sum regional crop yields for soft calibration grazing operation set drain depth for drainage water management flow diversion demand to m3 minimum flow rate (m3/s) below min - all flow to downstream channel (first outflow hydrograph in connect file) above min flow all flow diverted minimum - constant fraction demand is to fill to principal spillway set flow fractions in con file
minimum flow rate (m3/s) left in first outflow channel in connect file below min - all flow to downstream channel (first outflow hydrograph in connect file) above min flow - set first channel fraction to min and divert the rest to the second channel all flow to first outflow channel in connect file minimum or constant fraction set flow fractions to buffer tile and direct to channel xwalk with wetland.wet name xwalk with puddle.ops write to new landuse change file reset composite usle value - in hydro_init write to new landuse change file set new p factor reset composite usle value - in hydro_init write to new landuse change file set new p factor as function of slope - from cons_practice.lum relationship reset composite usle value - in hydro_init set new p factor as function of slope - from cons_practice.lum relationship adjust for pasture - above equation is for row crops reset composite usle value - in hydro_init set new p factor as function of slope - from cons_practice.lum relationship adjust for sod outlet - above equation is for underflow outlet reset composite usle value - in hydro_init set parameters for structural land use/managment write to new landuse change file set parameters for structural land use/managment set parameters for structural land use/managment set parameters for structural land use/managment set parameters for structural land use/managment begin and end monsoon initiation period
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ob_cur
integer, intent(in) :: ob_num
integer, intent(in) :: idtbl
Calls
Called by
Contents
None
Call graph
actions calls mgt_newtillmix_wet, amax1, wet_initial, hru_lum_init, pl_burnop, mgt_newtillmix, mgt_harvresidue, pest_apply, structure_set_parms, mgt_harvbiomass, hru_fr_change, pl_fert_wet, mgt_killop, plant_init, amin1, mgt_transplant, mgt_harvtuber, pl_graze, cn2_init, pl_fert, mgt_harvgrain, curno
wet_initial calls res_convert_mass
pl_burnop calls curno, hpc_d, hrc_d
mgt_newtillmix calls mgt_tillfactor
structure_set_parms calls ttcoef_wway
mgt_harvbiomass calls hpc_d, hrc_d
mgt_killop calls hpc_d, hrc_d, pl_rootfr
plant_init calls amin1, xmon, pl_partition, pl_root_gro, pl_seed_gro, float
mgt_transplant calls pl_partition, pl_root_gro, pl_seed_gro, float
mgt_harvtuber calls pl_rootfr
pl_graze calls amin1
cn2_init calls curno
mgt_harvgrain calls hpc_d
pl_root_gro calls amin1, float
mallo_control calls actions
wallo_demand calls actions
sd_channel_control2 calls actions
sd_channel_control3 calls actions, wallo_control
time_control calls actions, mallo_control, wallo_control, command
hru_control calls actions
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, command, calsoft_control
wallo_control calls wallo_demand
command calls sd_channel_control2, sd_channel_control3, hru_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq