allocate_parms – SWAT+
allocate_parms Subroutine
147 statements
Source File
subroutine allocate_parms()
Uses
hydrograph_module
time_module
hru_module
constituent_mass_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine allocates array sizes
~ ~ ~ INCOMING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
mhyd        |none          |max number of hydrographs
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
added for jaehak vars drains arrays for plant communities septic changes added 1/28/09 gsm added per JGA for Srini by gsm 9/8/2011 arrays for mangement output (output.mgt)
arrays which contain data related to years of rotation, grazings per year, and HRUs arrays which contain data related to HRUs Drainmod tile equations 01/2006 sj aug 09 end Arrays for subdaily erosion modeling by Jaehak Jeong By Zhang for C/N cycling ============================
zero reservoir module
Arguments
None
Calls
Called by
Contents
None
Call graph
allocate_parms calls zero0, zero1, zero2, zeroini
hru_read calls allocate_parms
proc_hru calls hru_read
main calls proc_hru