aqu_1d_control – SWAT+
aqu_1d_control Subroutine
274 statements
Source File
subroutine aqu_1d_control()
Uses
pesticide_data_module
maximum_data_module
salt_aquifer
constituent_mass_module
climate_module
cs_aquifer
aqu_pesticide_module
ch_pesticide_module
hydrograph_module
salt_module
time_module
aquifer_module
lag recharge from bottom of soil to water table ** disabled
add recharge to aquifer storage compute groundwater depth from surface compute flow and substract from storage set hydrograph flow from aquifer- convert mm to m3 compute seepage through aquifer and subtract from storage compute revap (deep root uptake from aquifer) and subtract from storage compute nitrate recharge into the aquifer compute nitrate return flow out of aquifer (kg/ha / mm) kg = (kg/ha / mm) * mm * ha compute NO3 lost in the aquifer compute nitrate seepage out of aquifer kg/ha = (kg/ha / mm) * mm compute mineral p flow (constant concentration) from aquifer - m^3 * ppm * 1000 kg/m^3 = 1/1000 temperature of aquifer flow compute fraction of flow to each channel in the aquifer if connected to aquifer - add flow find the first channel contributing set fractions for flow to each channel save hydrographs to distribute on following day compute pesticide transport and decay set initial pesticide at start of day add incoming pesticide to storage compute pesticide decay in the aquifer add decay to daughter pesticides compute pesticide in aquifer flow assume specific yield = upper limit (effective vs total porosity) and bulk density of 2.0 (ave of rock and soil - 2.65 and 1.35) mm = (mm/mm + (m^3/ton)*(ton/m^3)) * m * 1000. compute volume of flow through the layer - mm compute concentration in the flow return flow (1) and deep seepage (2) kg = kg/mm * mm set pesticide output variables - kg assume frsol = 1 (all soluble) all soluble - may add later compute outflow objects (flow to channels, reservoirs, or aquifer) if flow from hru is directly routed sum outflow to channels, reservoirs and other aquifers total ingoing and outgoing (retuen flow + percolation) for output to SWIFT
Arguments
None
Calls
Called by
Contents
None
Call graph
aqu_1d_control calls salt_chem_aqu, amin1, cs_rctn_aqu, cs_sorb_aqu
salt_chem_aqu calls ionic_strength, nacl, caco3, cationexchange, caso4, activity_coefficient, mgco3, mgso4
cs_rctn_aqu calls se_reactions_aquifer
command calls aqu_1d_control
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq