aqu_read_elements – SWAT+
aqu_read_elements Subroutine
150 statements
Source File
subroutine aqu_read_elements()
Uses
maximum_data_module
calibration_data_module
hydrograph_module
input_file_module
aquifer_module
allocate aquifer outputs for writing all hrus are in region setting up regions for aquifer soft cal and/or output by type all hrus are in region if no regions are input, don"t need elements read data for each element in all landscape cataloging units
Arguments
None
Calls
Called by
Contents
None
Call graph
aqu_read_elements calls define_unit_elements
proc_cal calls aqu_read_elements
main calls proc_cal