ascrv – SWAT+
ascrv Subroutine
14 statements
Source File
subroutine ascrv(x1, x2, x3, x4, x5, x6)
~ ~ ~ PURPOSE ~ ~ ~ this subroutine computes shape parameters x5 and x6 for the S curve equation x = y/(y + exp(x5 + x6*y)) given 2 (x,y) points along the curve. x5 is determined by solving the equation with x and y values measured around the midpoint of the curve (approx. 50% of the maximum value for x) and x6 is determined by solving the equation with x and y values measured close to one of the endpoints of the curve (100% of the maximum value for x) This subroutine is called from readbsn.f and readcrop.f
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x1
real, intent(in) :: x2
real, intent(in) :: x3
real, intent(in) :: x4
real, intent(out) :: x5
real, intent(out) :: x6
Called by
Contents
None
Call graph
hru_lte_read calls ascrv
topohyd_init calls ascrv
plantparm_init calls ascrv
caltsoft_hyd calls ascrv
main calls hru_lte_read, calsoft_control, proc_hru, proc_db
calsoft_control calls caltsoft_hyd
proc_hru calls topohyd_init
proc_db calls plantparm_init