cal_parm_select – SWAT+
cal_parm_select Subroutine
531 statements
Source File
subroutine cal_parm_select(ielem, ly, chg_parm, chg_typ, chg_val, absmin, absmax, num_db)
Uses
channel_module
basin_module
pesticide_data_module
soil_module
channel_data_module
conditional_module
plant_module
sd_channel_module
hru_lte_module
hydrograph_module
organic_mineral_mass_module
hru_module
reservoir_module
reservoir_data_module
aquifer_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine finds the current paramter value based on
user defined change
~ ~ ~ INCOMING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
val_cur     |variable      |current parameter value
                           |the standard temperature (20 degrees C)
chg         |data type     |contains information on variable change
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
HRU
don't change for tile ***Mike set epco parameter for each crop don't change for tile ***Mike define soil layer the drainage tile is in setting tile lage time SOL
BSN SWQ PST channel hydrology and sediment parms RES res decision tables AQU LTE initial soil properties
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ielem
integer, intent(in) :: ly
character(len=16), intent(in) :: chg_parm
character(len=16), intent(in) :: chg_typ
real, intent(in) :: chg_val
real, intent(in) :: absmin
real, intent(in) :: absmax
integer, intent(in) :: num_db
Calls
Called by
Contents
None
Call graph
cal_parm_select calls curno, amin1, soil_text_init, soil_awc_init
cal_conditions calls cal_parm_select
proc_cal calls cal_conditions
main calls proc_cal