cal_parmchg_read – SWAT+
cal_parmchg_read Subroutine
112 statements
Source File
subroutine cal_parmchg_read()
Uses
hydrograph_module
input_file_module
maximum_data_module
calibration_data_module
~ ~ ~ PURPOSE ~ ~ ~
this function computes new paramter value based on
user defined change
~ ~ ~ INCOMING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
val_cur     |variable      |current parameter value
                           |the standard temperature (20 degrees C)
chg         |data type     |contains information on variable change
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
read parameter change values for calibration crosswalk name with calibration parameter db allocate and read the conditions if no objects are specified - check all of them
Arguments
None
Calls
Called by
Contents
None
Call graph
cal_parmchg_read calls define_unit_elements
proc_cal calls cal_parmchg_read
main calls cal_parmchg_read, proc_cal