ch_rtpest – SWAT+
ch_rtpest Subroutine
150 statements
Source File
subroutine ch_rtpest()
Uses
channel_module
pesticide_data_module
constituent_mass_module
channel_data_module
sd_channel_module
ch_pesticide_module
hydrograph_module
 ~ ~ ~ PURPOSE ~ ~ ~
 this subroutine computes the daily stream pesticide balance
 (soluble and sorbed)
~ ~ ~ INCOMING VARIABLES ~ ~ ~
name          |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
chpst_conc(:) |mg/(m**3)     |initial pesticide concentration in reach
chpst_koc(:)  |m**3/g        |pesticide partition coefficient between
                             |water and sediment in reach
chpst_mix(:)  |m/day         |mixing velocity (diffusion/dispersion) for
                             |pesticide in reach
chpst_rea(:)  |1/day         |pesticide reaction coefficient in reach
chpst_rsp(:)  |m/day         |resuspension velocity in reach for pesticide
                             |sorbed to sediment
chpst_stl(:)  |m/day         |settling velocity in reach for pesticide
                             |sorbed to sediment
chpst_vol(:)  |m/day         |pesticide volatilization coefficient in
                             |reach
drift(:)      |kg            |amount of pesticide drifting onto main
                             |channel in subbasin
rchdep        |m             |depth of flow on day
rchwtr        |m^3 H2O       |water stored in reach at beginning of day
sedpst_rea(:) |1/day         |pesticide reaction coefficient in river bed
                             |sediment
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
bury        |mg pst        |loss of pesticide from active sediment layer
                           |by burial
difus       |mg pst        |diffusion of pesticide from sediment to reach
reactb      |mg pst        |amount of pesticide in sediment that is lost
                           |through reactions
reactw      |mg pst        |amount of pesticide in reach that is lost
                           |through reactions
resuspst    |mg pst        |amount of pesticide moving from sediment to
                           |reach due to resuspension
setlpst     |mg pst        |amount of pesticide moving from water to
                           |sediment due to settling
solpesto    |mg pst/m^3    |soluble pesticide concentration in outflow
                           |on day
sorpesto    |mg pst/m^3    |sorbed pesticide concentration in outflow
                           |on day
volatpst    |mg pst        |amount of pesticide in reach lost by
                           |volatilization
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
chpstmass   |mg pst        |mass of pesticide in reach
depth       |m             |depth of water in reach
fd2         |
frsol       |none          |fraction of pesticide in reach that is soluble
frsrb       |none          |fraction of pesticide in reach that is sorbed
jrch        |none          |reach number
pstin       |mg pst        |total pesticide transported into reach
                           |during time step
sedcon      |g/m^3         |sediment concentration
sedpstmass  |mg pst        |mass of pesticide in bed sediment
solpstin    |mg pst        |soluble pesticide entering reach during
                           |time step
sorpstin    |mg pst        |sorbed pesticide entering reach during
                           |time step
tday        |days          |flow duration
wtrin       |m^3 H2O       |volume of water entering reach during time
                           |step
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~
Intrinsic: Abs
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
initialize depth of water for pesticide calculations volume of water entering reach and stored in reach pesticide transported into reach during day calculate mass of pesticide in reach calculate mass of pesticide in bed sediment in-stream processes calculate sediment concentration set kd calculate fraction of soluble and sorbed pesticide ASSUME DENSITY=2.6E6; KD2=KD1 calculate flow duration calculate amount of pesticide that undergoes chemical or biological degradation on day in reach add decay to daughter pesticides calculate amount of pesticide that volatilizes from reach calculate amount of pesticide removed from reach by settling calculate resuspension of pesticide in reach calculate diffusion of pesticide between reach and sediment calculate removal of pesticide from active sediment layer by burial verify that water concentration is at or below solubility insignificant flow benthic processes calculate loss of pesticide from bed sediments by reaction add decay to daughter pesticides set new pesticide mass of (in + store) after processes calculate outflow and storage in water column
Arguments
None
Called by
Contents
None
Call graph
sd_channel_control3 calls ch_rtpest
sd_channel_control2 calls ch_rtpest
command calls sd_channel_control3, sd_channel_control2
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq