ch_rtmusk – SWAT+
ch_rtmusk Subroutine
223 statements
Source File
subroutine ch_rtmusk()
Uses
channel_module
basin_module
water_body_module
channel_data_module
conditional_module
climate_module
channel_velocity_module
sd_channel_module
hydrograph_module
time_module
hru_module
reservoir_module
reservoir_data_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine routes a daily flow through a reach using the
Muskingum method
code provided by Dr. Valentina Krysanova, Pottsdam Institute for
Climate Impact Research, Germany
Modified by Balaji Narasimhan
Spatial Sciences Laboratory, Texas A&M University
jga ob(icmd)%tsin = (/0., 800., 2000., 4200., 5200., 4400., 3200., 2500., 2000., 1500., 1000., 700., 400., & 0., 0., 0., 0., 0., 1000000., 1000000., 1000000., 1000000., 1000000., 1000000./) total wetland volume at start of day subdaily time step water entering reach during time step - substeps for stability interpolate rating curve using inflow rates save variables at each routing time step for sediment routing add inflow to total storage if no water in channel - skip routing and set rating curves to zero Muskingum flood routing method save inflow/outflow volumes for next time step (and day) for Muskingum Variable Storage Coefficent method - sc=2dt/(2ttime+dt) - ttime=(in2+out1)/2 compute outflow rating curve for next time step add outflow to daily hydrograph and subdaily flow subtract outflow from total storage set rating curve for next time step partition channel and flood plain based on bankfull volume fill channel to bank full if below if flood plain link - fill wetlands to emergency if flood plain storage available wetland storage can't go above emergency in release dtbl - it becomes flood plain storage compute water balance - precip, evap and seep km * m * 1000 m/km * ha/10000 m2 = ha m3 = 10. * mm * ha add precip calculate transmission losses mm/hr * km * m * 24 / nsteps = m3 subtract transmission loses from outflow calculate evaporation losses calculate width of channel at water level - flood plain evap calculated in wetlands mm/day * m2 / (1000. * sd_ch(jrch)%msk%nsteps) check water balance at end of day total wetland volume at end of day
Arguments
None
Calls
Called by
Contents
None
Call graph
ch_rtmusk calls rcurv_interp_flo
rcurv_interp_flo calls chrc_interp
sd_channel_control3 calls ch_rtmusk
channel_control calls ch_rtmusk
sd_channel_control2 calls ch_rtmusk
command calls sd_channel_control3, sd_channel_control2
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq