channel_control – SWAT+
channel_control Subroutine
122 statements
Source File
subroutine channel_control()
Uses
channel_module
basin_module
constituent_mass_module
channel_data_module
climate_module
hydrograph_module
time_module
~ ~ ~ PURPOSE ~ ~ ~ this subroutine simulates channel routing
~ ~ ~ INCOMING VARIABLES ~ ~ ~ name |units |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ bankst(:) |m^3 H2O |bank storage inum1 |none |reach number inum2 |none |inflow hydrograph storage location number pet_ch |mm H2O |potential evapotranspiration on day rchdep |m |depth of flow on day rttlc |m^3 H2O |transmission losses from reach on day rtwtr |m^3 H2O |water leaving reach on day ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ OUTGOING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ revapday |m^3 H2O |amount of water moving from bank storage |into the soil profile or being taken |up by plant roots in the bank storage zone rtwtr |m^3 H2O |water leaving reach on day qdbank |m^3 H2O |streamflow contribution from bank storage sedrch |metric tons |sediment transported out of reach on day ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ii |none |counter jrch |none |reach number ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~ Intrinsic: Min SWAT: rchinit, rtover, rtday, rtmusk, rthourly, rtsed, rthsed, watqual SWAT: noqual, hhwatqual, hhnoqual, rtpest, rthpest SWAT: rchuse, reachout
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
initialize variables for route command loop zero flow out variables route water through reach route water through reach initialize inflow concentrations
average daily water depth for sandi doty 09/26/07 add transmission losses to bank storage/deep aquifer in subbasin compute revap from bank storage compute contribution of water in bank storage to streamflow Channel Deposition (Only new deposits during the current time step) Floodplain Deposition (Only new deposits during the current time step) Total suspended sediments (only silt and clay)
Arguments
None
Calls
Contents
None
Call graph
channel_control calls ch_rchinit, ch_rtmusk, ch_rtday
ch_rtmusk calls rcurv_interp_flo
rcurv_interp_flo calls chrc_interp