cli_bounds_check – SWAT+
cli_bounds_check Subroutine
29 statements
Source File
subroutine cli_bounds_check(st_day, st_yr, end_day, end_yr, out_bounds)
Uses
time_module
climate_module
~ ~ ~ PURPOSE ~ ~ ~ this subroutine checks to see if climate data is in current simulation day
check if climate data starts after simulation
Arguments
Type Intent Optional Attributes Name
integer :: st_day
integer :: st_yr
integer :: end_day
integer :: end_yr
check id climate data starts before simulation
character(len=1) :: out_bounds
Called by
Contents
None
Call graph
cli_precip_control calls cli_bounds_check
climate_control calls cli_bounds_check, cli_precip_control
time_control calls cli_precip_control, climate_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, calsoft_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq