cli_pgen – SWAT+
cli_pgen Subroutine
37 statements
Source File
subroutine cli_pgen(iwgn)
Uses
basin_module
time_module
climate_module
hydrograph_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine generates precipitation data when the user chooses to
simulate or when data is missing for particular days in the weather file
~ ~ ~ INCOMING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
j           |none          |HRU number
pr_w(1,:,:) |none          |probability of wet day after dry day in month
pr_w(2,:,:) |none          |probability of wet day after wet day in month
rnd3(:)     |none          |random number between 0.0 and 1.0
rndseed(:,:)|none          |random number seeds
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
rnd3(:)     |none          |random number between 0.0 and 1.0
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~
Intrinsic: Log
SWAT: Aunif, Dstn1
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
skewed rainfall distribution precip for the next day
Arguments
Type Intent Optional Attributes Name
integer :: iwgn
Called by
Contents
None
Call graph
cli_precip_control calls cli_pgen
time_control calls cli_precip_control, climate_control
climate_control calls cli_precip_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, calsoft_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq