cli_wndgen – SWAT+
cli_wndgen Subroutine
44 statements
Source File
subroutine cli_wndgen(iwgn)
Uses
hydrograph_module
time_module
climate_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine generates wind speed
~ ~ ~ INCOMING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
idg(:)      |none          |array location of random number seed used
                           |for a given process
j           |none          |HRU number
rndseed(:,:)|none          |random number seeds
wndav(:,:)  |m/s           |average wind speed for the month in HRU
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~
Intrinsic: Log
SWAT: Aunif
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
Generate wind speed !! Generate wind direction !! ! set to zero, no longer attempt to read in
Arguments
Type Intent Optional Attributes Name
integer :: iwgn
Calls
Called by
Contents
None
Call graph
cli_wndgen calls float
climate_control calls cli_wndgen
time_control calls climate_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, calsoft_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq