cli_lapse – SWAT+
cli_lapse Subroutine
28 statements
Source File
subroutine cli_lapse()
Uses
basin_module
climate_module
hydrograph_module
~ ~ ~ PURPOSE ~ ~ ~ this subroutine adjusts precip and temperature for elevation
adjust precip and temperature for elevation using lapse rates
Arguments
None
Called by
Contents
None
Call graph
sd_channel_control3 calls cli_lapse
main calls cli_lapse, command, time_control, calhard_control, calsoft_control
res_control calls cli_lapse
command calls sd_channel_control3, res_control
time_control calls command
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq