climate_control – SWAT+
climate_control Subroutine
201 statements
Source File
subroutine climate_control()
Uses
basin_module
maximum_data_module
climate_module
hydrograph_module
time_module
~ ~ ~ PURPOSE ~ ~ ~ this subroutine controls weather inputs to SWAT. Precipitation and temperature data is read in and the weather generator is called to fill in radiation, wind speed and relative humidity as well as missing precipitation and temperatures. Adjustments for climate changes studies are also made in this subroutine.
~ ~ ~ INCOMING VARIABLES ~ ~ ~ name |units |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ elevp(:) |m |elevation of precipitation gage station elevt(:) |m |elevation of temperature gage station welev(:) |m |elevation of weather station used to compile |weather generator data ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~ Intrinsic: Max, Min SWAT: pmeas, tmeas, smeas, hmeas, wmeas SWAT: pgen, tgen, weatgn, clgen, slrgen, rhgen, wndgen
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
Temperature: Solar Radiation: Relative Humidity: simple dewpoint eqn from Lawrence 2005. Bull. Amer. Meteor. Soc. Wind Speed: Potential ET: Read in data !! if using a measured data Use HARGREAVES POTENTIAL EVAPOTRANSPIRATION METHOD Update CMI and Precip minus PET 30 day moving sum calculate climatic moisture index - cumulative p/pet Use Hargreaves Potential ET Method subtract the 30 day previous and add the current day precip/pet Calculate air temperature lag day for stream temperature replace current day temperature lag day is the next variable in array Calculate maximum half-hour rainfall fraction Base Zero Heat Units Climate Change Adjustments !!
Arguments
None
Calls
Called by
Contents
None
Call graph
climate_control calls cli_clgen, cli_rhgen, cli_tgen, cli_precip_control, cli_weatgn, cli_bounds_check, cli_slrgen, cli_wndgen
cli_precip_control calls cli_bounds_check, cli_pgen, cli_pgenhr
cli_wndgen calls float
time_control calls climate_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, calsoft_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq