command – SWAT+
command Subroutine
483 statements
Source File
subroutine command()
Uses
channel_module
ru_module
basin_module
maximum_data_module
constituent_mass_module
soil_module
sd_channel_module
hydrograph_module
hru_lte_module
time_module
organic_mineral_mass_module
hru_module
reservoir_module
gwflow_module
aquifer_module
~ ~ ~ PURPOSE ~ ~ ~ for every day of simulation, this subroutine steps through the command lines in the watershed configuration (.fig) file. Depending on the command code on the .fig file line, a command loop is accessed ~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~ SWAT: subbasin, route, routres, transfer, recmon SWAT: recepic, save, recday, recyear
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
hru and ru can have hyrdographs that lag into next day assume only one day is saved for all other objects if incoming object is not an hru or ru, send total hyd to surface runoff multiply inflow hyd by the fraction of incoming add flow hydrographs for each incoming object artificial channel - length=0 - no transformations output channel morphology compute flashiness index write object output for entire simulation print all output files print water allocation output print manure allocation output carbon output for testing ***jga write carbon in soil, plant, and residue at end of the day write carbon in soil, plant, and residue at end the month
write carbon in soil, plant, and residue at end of year
write carbon in soil, plant, and residue at end the simulation
Arguments
None
Calls
Called by
Contents
None
Call graph
command calls ru_control, recall_salt, obj_output, hru_lte_control, wetland_output, aquifer_output, cs_str_output, ru_salt_output, basin_ls_pest_output, basin_sdchannel_output, gwflow_simulate, sd_channel_control3, manure_demand_output, aqu_cs_output, aqu_pesticide_output, sd_chanmorph_output, res_cs_output, ru_cs_output, basin_aquifer_output, basin_reservoir_output, flow_dur_curve, hru_pathogen_output, cha_pesticide_output, basin_ch_pest_output, basin_chanbud_output, water_allocation_output, recall_cs, hru_carbon_output, aqu_salt_output, reservoir_output, basin_aqu_pest_output, cs_balance, aqu_1d_control, sd_channel_control2, hru_lte_output, wet_salt_output, wet_cs_output, soil_nutcarb_write, sd_chanbud_output, recall_output, basin_channel_output, salt_balance, hru_control, constit_hyd_mult, hydout_output, hru_cs_output, ch_salt_output, ch_cs_output, basin_res_pest_output, basin_recall_output, basin_chanmorph_output, manure_source_output, hru_salt_output, channel_output, res_pesticide_output, res_salt_output, ru_output, basin_output, 1000, hyddep_output, res_control, recall_nut, sd_channel_control, hru_output, hru_pesticide_output, sd_channel_output, hydin_output, lsu_output
wetland_output calls float
aquifer_output calls float
basin_ls_pest_output calls float
basin_sdchannel_output calls float
gwflow_simulate calls 1000, 10000, gwflow_chem, 50, gwflow_canl_out, gwflow_rech, gwflow_gwet, gwflow_ppex
sd_channel_control3 calls cli_lapse, ch_rtpath, gwflow_gwsw, gwflow_canl, actions, gwflow_tile, gwflow_satx, ch_rtmusk, sd_channel_sediment3, wallo_control, ch_rtpest, conditions
aqu_cs_output calls float
aqu_pesticide_output calls float
sd_chanmorph_output calls float
res_cs_output calls float
basin_aquifer_output calls float
basin_reservoir_output calls float
flow_dur_curve calls amin1, float
hru_pathogen_output calls float
cha_pesticide_output calls float
basin_ch_pest_output calls float
hru_carbon_output calls hrc_a, hpc_d, hpc_m, hpc_y, hsc_d, hpc_a, hsc_m, hscf_d, hsc_y, hscf_m, hsc_a, hscf_y, hrc_d, hscf_a, hrc_m, hrc_y
aqu_salt_output calls float
reservoir_output calls float
basin_aqu_pest_output calls float
cs_balance calls float
aqu_1d_control calls salt_chem_aqu, cs_rctn_aqu, amin1, cs_sorb_aqu
sd_channel_control2 calls sd_channel_sediment, hyd_convert_conc_to_mass, ch_rtpath, hyd_convert_mass_to_conc, ch_watqual4, actions, ch_rtmusk, ch_rtpest, conditions
hru_lte_output calls float
wet_salt_output calls float
wet_cs_output calls float
salt_balance calls float
hru_control calls cbn_zhang2, cs_rctn_hru, sq_canopyint, nut_nrain, pest_decay, hru_urb_bmp, wet_irrp, cs_rain, nut_nitvol, hpc_d, nut_nlch, salt_roadsalt, sq_surfst, hru_hyds, sep_biozone, swr_latsed, cs_sorb_hru, nut_orgn, nut_solp, varinit, swr_percmain, pl_grow, pl_community, path_ls_swrouting, actions, rls_routetile, salt_lch, hsc_d, nut_pminrl2, pest_washp, stmp_solt, pl_graze, swr_subwq, path_ls_runoff, salt_rain, hru_urbanhr, pest_pl_up, swr_substor, hscf_d, sq_snom, path_ls_process, nut_nminrl, nut_pminrl, pest_lch, rls_routesurf, hru_urban, nut_orgnc, pest_soil_tot, stor_surfstor, smp_filter, sq_crackvol, surface, wetland_control, hrc_d, pest_enrsb, et_pot, smp_buffer, rls_routesoil, albedo, pest_pesty, conditions, et_act, nut_psed, smp_grass_wway, salt_chem_hru, rls_routeaqu, nut_orgnc2, pl_fert, mgt_operatn, cs_lch, smp_bmpfixed
hru_cs_output calls float
ch_salt_output calls float
ch_cs_output calls float
basin_res_pest_output calls float
basin_chanmorph_output calls float
hru_salt_output calls float
res_pesticide_output calls float
res_salt_output calls float
basin_output calls float
res_control calls cli_lapse, res_hydro, res_sediment, res_nutrient, res_rel_conds, res_pest, res_salt, conditions, res_cs
hru_output calls float
hru_pesticide_output calls float
sd_channel_output calls float
lsu_output calls float
cs_rctn_hru calls se_reactions_soil
nut_nrain calls float
cs_rain calls float
ch_rtpath calls theta
salt_roadsalt calls float
hru_hyds calls float, min1, flow_hyd_ru_hru
ch_watqual4 calls amin1
swr_percmain calls amin1, swr_drains, swr_percmicro, swr_satexcess, gwflow_soil, swr_origtile, swr_percmacro
pl_grow calls pl_dormant, pl_seed_gro, pl_biomass_gro, pl_mortality, pl_leaf_senes, pl_partition, pl_leaf_gro, pl_nut_demand, pl_root_gro
pl_community calls pl_waterup
actions calls pl_graze, amin1, pl_fert, mgt_newtillmix_wet, amax1, wet_initial, hru_lum_init, pl_burnop, mgt_newtillmix, mgt_harvresidue, pest_apply, structure_set_parms, mgt_harvbiomass, hru_fr_change, pl_fert_wet, mgt_killop, plant_init, mgt_transplant, mgt_harvtuber, cn2_init, mgt_harvgrain, curno
salt_chem_aqu calls nacl, activity_coefficient, caso4, caco3, cationexchange, mgso4, ionic_strength, mgco3
res_nutrient calls amin1
nut_pminrl2 calls alog
cs_rctn_aqu calls se_reactions_aquifer
pl_graze calls amin1
swr_subwq calls hsc_d
salt_rain calls float
hru_urbanhr calls hru_sweep
ch_rtmusk calls rcurv_interp_flo
res_rel_conds calls cond_real_c, cond_integer_c
sd_channel_sediment3 calls rcurv_interp_flo, amax1
surface calls ero_ysed, sq_volq, ero_eiusle, ero_pkq, sq_dailycn, sq_crackflow, ero_ovrsed, ero_cfactor
wetland_control calls res_hydro, res_sediment, res_nutrient, conditions, wet_cs, gwflow_wetl, wet_salt, ero_cfactor
res_pest calls amin1
wallo_control calls wallo_demand, wallo_transfer, wallo_withdraw, wallo_treatment, salt_irrig, cs_irrig
conditions calls float, cond_real, cond_integer
et_act calls amin1
nut_psed calls amin1
salt_chem_hru calls 50, nacl, activity_coefficient, caso4, caco3, cationexchange, mgso4, ionic_strength, mgco3
nut_orgnc2 calls hsc_d
mgt_operatn calls mgt_sched
swr_drains calls swr_depstor
rcurv_interp_flo calls chrc_interp
wallo_demand calls actions, conditions
pl_dormant calls amin1
wet_initial calls res_convert_mass
pl_burnop calls hpc_d, hrc_d, curno
sq_volq calls sq_greenampt, sq_daycn
pl_biomass_gro calls hpc_d, pl_tstr, cs_uptake, pl_nup, salt_uptake, pl_pup
pl_mortality calls amin1
mgt_newtillmix calls mgt_tillfactor
structure_set_parms calls ttcoef_wway
swr_satexcess calls amin1
mgt_harvbiomass calls hpc_d, hrc_d
wallo_withdraw calls gwflow_ppag
pl_leaf_senes calls hpc_d, amin1, hrc_d
mgt_killop calls hpc_d, hrc_d, pl_rootfr
plant_init calls amin1, float, pl_seed_gro, pl_partition, pl_root_gro, xmon
pl_leaf_gro calls amin1, float, alog10
mgt_transplant calls float, pl_seed_gro, pl_partition, pl_root_gro
mgt_harvtuber calls pl_rootfr
wallo_treatment calls hyd_convert_conc_to_mass
mgt_sched calls pl_fert, mgt_newtillmix_wet, pl_burnop, mgt_newtillmix, mgt_harvresidue, pest_apply, mgt_harvbiomass, pl_fert_wet, mgt_killop, mgt_transplant, mgt_harvtuber, mgt_harvgrain, curno, salt_fert_wet, cs_fert_wet, mgt_plantop, cs_fert, salt_fert
pl_nut_demand calls pl_nupd, pl_pupd
pl_root_gro calls amin1, float
pl_waterup calls amin1, salt_chem_soil_single
cn2_init calls curno
mgt_harvgrain calls hpc_d
pl_tstr calls amin1
salt_chem_soil_single calls nacl, activity_coefficient, caso4, caco3, mgso4, ionic_strength, mgco3
pl_nup calls amin1, pl_nfix, nuts
pl_nupd calls float
pl_pup calls nuts
pl_pupd calls float
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq