dr_db_read – SWAT+
dr_db_read Subroutine
47 statements
Source File
subroutine dr_db_read()
Uses
dr_module
input_file_module
maximum_data_module
constituent_mass_module
Arguments
None
Calls
Called by
Contents
None
Call graph
dr_db_read calls dr_read_om, dr_path_read, dr_read_salt, dr_read_hmet, dr_read_pest
hyd_connect calls dr_db_read
main calls dr_db_read, hyd_connect