dr_read_hmet – SWAT+
dr_read_hmet Subroutine
68 statements
Source File
subroutine dr_read_hmet()
Uses
dr_module
maximum_data_module
constituent_mass_module
hydrograph_module
input_file_module
organic_mineral_mass_module
Arguments
None
Called by
Contents
None
Call graph
dr_db_read calls dr_read_hmet
hyd_connect calls dr_db_read
main calls dr_db_read, hyd_connect