ero_ovrsed – SWAT+
ero_ovrsed Subroutine
110 statements
Source File
subroutine ero_ovrsed()
Uses
basin_module
soil_module
urban_data_module
plant_module
climate_module
hydrograph_module
time_module
organic_mineral_mass_module
hru_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine computes splash erosion by raindrop impact and flow erosion by overland flow
~ ~ ~ INCOMING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
hhqday(:)   |mm H2O        |surface runoff generated each timestep
                           |of day in HRU
hru_km(:)   |km2           |area of HRU in square kilometers
rwst(:)%weat%ts(:)  |mm H2O        |precipitation for the time step during the
                           |day in HRU
eros_spl      |none          |coefficient of splash erosion varing 0.9-3.1
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
hhsedy(:,:)|tons           |sediment yield from HRU drung a time step
                           |applied to HRU
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
jj          |none          |HRU number
kk          |none          |time step of the day
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~
Intrinsic: log10, Exp, Real
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
Splash erosion model is adopted from EUROSEM model developed by Morgan (2001). Rill/interill erosion model is adoped from Modified ANSWERS model by Park et al.(1982) Code developed by J. Jeong and N. Kannan, BRC.
Fraction of sand Soil detachability values adopted from EUROSEM User Guide (Table 1) canopy cover based on leaf area index canopy cover is assumed to be 100% if LAI>=1 Rainfall kinetic energy generated by direct throughfall (J/m^2/mm) Rainfall kinetic energy generated by leaf drainage (J/m^2) Depth of rainfall total kinetic energy by rainfall (J/m^2) total soil detachment by raindrop impact Impervious area of HRU maximum water depth that allows splash erosion Overland flow erosion cover and management factor used in usle equation (ysed.f) specific weight of water at 5 centigrate =9807N/m3 Impervious area of HRU
Arguments
None
Called by
Contents
None
Call graph
surface calls ero_ovrsed
hru_control calls surface
command calls hru_control
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq