gcycl – SWAT+
gcycl Subroutine
60 statements
Source File
subroutine gcycl()
Uses
basin_module
maximum_data_module
conditional_module
climate_module
~ ~ ~ PURPOSE ~ ~ ~ This subroutine initializes the random number seeds. If the user desires a different set of random numbers for each simulation run, the random number generator is used to reset the values of the seeds.
~ ~ ~ INCOMING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ OUTGOING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ idg(:) |none |array location of random number seed used |for a given process rndseed(:,:)|none |random number seeds. The seeds in the array |are used to generate random numbers for the |following purposes |(1) wet/dry day probability |(2) solar radiation |(3) precipitation |(4) USLE rainfall erosion index |(5) wind speed |(6) 0.5 hr rainfall fraction |(7) relative humidity |(8) maximum temperature |(9) minimum temperature |(10) generate new random numbers ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~ SWAT: Aunif
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
initialize random number seeds
assign new random number seeds shuffle random number for conditional probablility assign random number for decision table conditional shuffle seeds randomly (Bratley, Fox, Schrage, p34) assign half-hour maximum rainfall seed to second array location for use in sub-daily pcp generator
Arguments
None
Called by
Contents
None
Call graph
cli_wgnread calls gcycl
proc_date_time calls cli_wgnread
main calls proc_date_time