gwflow_read – SWAT+
gwflow_read Subroutine
1964 statements
Source File
subroutine gwflow_read()
Uses
maximum_data_module
cs_data_module
constituent_mass_module
sd_channel_module
hydrograph_module
hru_module
gwflow_module
reservoir_data_module
Arguments
None
Calls
Called by
Contents
None
Call graph
gwflow_read calls 10, 10000, 50, 1000
hyd_connect calls gwflow_read
main calls hyd_connect