gwflow_gwsw – SWAT+
gwflow_gwsw Subroutine
154 statements
Source File
subroutine gwflow_gwsw(chan_id)
Uses
gwflow_module
hydrograph_module
sd_channel_module
constituent_mass_module
~ ~ ~ PURPOSE ~ ~ ~ this subroutine calculates the water exchange volume between the channel and the connected grid cells (exchange volumes are used in gwflow_simulate, in groundwater balance equations)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: chan_id
Called by
Contents
None
Call graph
sd_channel_control3 calls gwflow_gwsw
command calls sd_channel_control3
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq