gwflow_ppag – SWAT+
gwflow_ppag Subroutine
115 statements
Source File
subroutine gwflow_ppag(hru_id, hru_demand, extracted, dmd_unmet)
Uses
constituent_mass_module
res_cs_module
cs_module
hydrograph_module
salt_module
organic_mineral_mass_module
hru_module
gwflow_module
res_salt_module
~ ~ ~ PURPOSE ~ ~ ~ this subroutine determines the volume of groundwater that is extracted from gwflow grid cells (pumping volume are used in gwflow_simulate, in groundwater balance equations)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: hru_id
real, intent(in) :: hru_demand
real, intent(inout) :: extracted
real, intent(inout) :: dmd_unmet
Called by
Contents
None
Call graph
wallo_withdraw calls gwflow_ppag
wallo_control calls wallo_withdraw
sd_channel_control3 calls wallo_control
time_control calls wallo_control, command
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, command, calsoft_control
command calls sd_channel_control3
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq