hru_fr_change – SWAT+
hru_fr_change Subroutine
104 statements
Source File
subroutine hru_fr_change(lsu_elem_upd, ru_elem_upd)
Uses
dr_module
ru_module
maximum_data_module
calibration_data_module
hydrograph_module
hru_module
reservoir_module
reservoir_data_module
read data for each element in all routing units dr_om_num was previously xwalked with dr_db()%om_file read data for each element in all landscape cataloging units set new hru areas reset wetland parameters reset volumes and surface areas hamm10. => m**3 - assume entire hru is wet and don't use fractional inputs (for simplicity) compute weighted Mannings n for each subbasin
Arguments
Type Intent Optional Attributes Name
character(len=25), intent(in) :: lsu_elem_upd
character(len=25), intent(in) :: ru_elem_upd
Called by
Contents
None
Call graph
actions calls hru_fr_change
mallo_control calls actions
wallo_demand calls actions
sd_channel_control2 calls actions
sd_channel_control3 calls actions, wallo_control
time_control calls actions, mallo_control, wallo_control, command
hru_control calls actions
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, command, calsoft_control
wallo_control calls wallo_demand
command calls sd_channel_control2, sd_channel_control3, hru_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq