hru_carbon_output – SWAT+
hru_carbon_output Subroutine
104 statements
Source File
subroutine hru_carbon_output(ihru)
Uses
basin_module
output_landscape_module
soil_module
plant_module
plant_data_module
hydrograph_module
time_module
organic_mineral_mass_module
carbon_module
hru_module
!!!! added for new output write
daily print soil carbon gain/loss residue carbon gain/loss plant carbon gain/loss soil transformations
soil carbon gain/loss residue carbon gain/loss plant carbon gain/loss soil transformations
check end of month monthly print soil carbon gain/loss residue carbon gain/loss plant carbon gain/loss soil transformations
soil carbon gain/loss residue carbon gain/loss plant carbon gain/loss soil transformations
check end of year yearly print soil carbon gain/loss residue carbon gain/loss residue carbon gain/loss soil transformations
soil carbon gain/loss residue carbon gain/loss plant carbon gain/loss soil transformations
average annual print soil carbon gain/loss residue carbon gain/loss plant carbon gain/loss soil transformations
soil carbon gain/loss residue carbon gain/loss plant carbon gain/loss soil transformations
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ihru
Calls
Called by
Contents
None
Call graph
hru_carbon_output calls hrc_d, hscf_d, hsc_y, hpc_d, hsc_d, hrc_y, hpc_y, hscf_y, hsc_m, hpc_m, hrc_m, hscf_m, hsc_a, hrc_a, hpc_a, hscf_a
command calls hru_carbon_output
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq