hru_control – SWAT+
hru_control Subroutine
592 statements
Source File
subroutine hru_control()
Uses
output_ls_pesticide_module
constituent_mass_module
climate_module
salt_module
time_module
carbon_module
gwflow_module
reservoir_data_module
basin_module
output_landscape_module
conditional_module
plant_data_module
cs_module
hydrograph_module
organic_mineral_mass_module
septic_data_module
plant_module
mgt_operations_module
soil_module
water_body_module
hru_module
reservoir_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine controls the simulation of the land phase of the
hydrologic cycle
adjust precip and temperature for elevation using lapse rates zero pesticide balance variables zero all variables except pest in soil and in/on plant ht1== deposition: write to deposition.out ht2== outflow from inflow: added to hru generated flows check auto operations check day of future fertilizer application if end of year, reset the one time operation per year increment days since last plant and harvest update base zero total heat units zero stresses calculate albedo for day calculate soil temperature for soil layers compute canopy interception compute snow melt route overland flow across hru - add tile flow if not subirrigation or saturated buffer route incoming surface runoff add surface runon to wetland route across hru - infiltrate and deposit sediment add lateral flow soil water Route incoming lateral soil flow add tile flow to tile (subirrigation and saturated buffer) add aquifer flow to bottom soil layer and redistribute upwards Route incoming aquifer flow compute crack volume compute evapotranspiration perform management operations compute surface runoff processes if wetland - no runoff or sediment yield - all constituents transported in surface runoff and sediment will be zero ht2%sed==sediment routed across hru from surface runon check wetland/paddy continuous irrigation Jaehak 2023 manual irrigation on if ponding depth is lower than the threshold depth wetland/paddy processes compute effective rainfall (amount that percs into soil) for wetland use seepage into soil from ponded water no wetland (no ponded water) add irrigation to subdaily effective precip perform soil water routing compute peak rate similar to swat-deg using SCS triangular unit hydrograph
graze only if adequate biomass in HRU if total above ground biomass is available - graze check to set if grazing period is over compute nitrogen and phosphorus mineralization compute biozone processes in septic HRUs if 1) current is septic hru and 2) soil temperature is above zero compute plant community partitions check irrigation demand decision table for water allocation (after adding irrigation) iauto points to pcom(j)%dtbl(iauto) for days between operation check monsoon season for tropical plants compute plant biomass, leaf, root and seed growth reset harvested biomass and number of harvests for yearly yield output compute total parms for all plants in the community compute aoil water content to 300 mm depth compute total surface residue compute actual ET for day in HRU compute pesticide washoff
compute pesticide uptake compute pesticide degradation compute pesticide movement in soil sum total pesticide in soil Add by zhang ==================== Add by zhang ====================
add nitrate in rainfall to soil profile compute nitrate movement leaching compute phosphorus movement compute chl-a, CBOD and dissolved oxygen loadings compute pathogen transport compute loadings from urban areas compute sediment loading in lateral flow and add to sedyld lag nutrients and sediment in surface runoff lag subsurface flow and nitrate in subsurface flow compute reduction in pollutants due to edge-of-field filter strip compute reduction in pollutants due to in field grass waterway compute reduction in pollutants due to in fixed BMP eff ht2%flo is outflow from wetland or total saturation excess if no wetland mm = m3/ha ha/10000m2 1000mm/m calculate amount of surface runoff during day (qday) and store the remainder compute water yield for HRU add evap from impounded water (wetland) to et and esoil set hydrographs for direct routing or landscape unit
Arguments
None
Calls
Called by
Contents
None
Call graph
hru_control calls hscf_d, sq_snom, varinit, swr_percmain, hrc_d, cbn_zhang2, pl_grow, pest_enrsb, path_ls_process, cs_rctn_hru, sq_canopyint, et_pot, nut_nminrl, pl_community, pest_decay, nut_nrain, smp_buffer, actions, rls_routesoil, wet_irrp, nut_pminrl, pest_lch, path_ls_swrouting, hru_urb_bmp, hru_urbanhr, albedo, rls_routesurf, rls_routetile, nut_nitvol, pest_pesty, nut_orgnc, salt_lch, cs_rain, hru_urban, hsc_d, hpc_d, conditions, et_act, nut_pminrl2, pest_washp, nut_psed, nut_nlch, smp_grass_wway, swr_latsed, stmp_solt, pl_graze, pest_soil_tot, salt_roadsalt, swr_subwq, path_ls_runoff, sq_surfst, hru_hyds, stor_surfstor, smp_filter, salt_chem_hru, rls_routeaqu, sq_crackvol, surface, wetland_control, sep_biozone, nut_orgnc2, salt_rain, pl_fert, cs_sorb_hru, mgt_operatn, pest_pl_up, nut_orgn, nut_solp, cs_lch, swr_substor, smp_bmpfixed
swr_percmain calls swr_drains, swr_percmicro, swr_satexcess, gwflow_soil, amin1, swr_origtile, swr_percmacro
pl_grow calls pl_dormant, pl_seed_gro, pl_biomass_gro, pl_mortality, pl_leaf_senes, pl_partition, pl_leaf_gro, pl_nut_demand, pl_root_gro
cs_rctn_hru calls se_reactions_soil
pl_community calls pl_waterup
nut_nrain calls float
actions calls pl_graze, pl_fert, mgt_newtillmix_wet, amax1, wet_initial, hru_lum_init, pl_burnop, mgt_newtillmix, mgt_harvresidue, pest_apply, structure_set_parms, mgt_harvbiomass, hru_fr_change, pl_fert_wet, mgt_killop, plant_init, amin1, mgt_transplant, mgt_harvtuber, cn2_init, mgt_harvgrain, curno
hru_urbanhr calls hru_sweep
cs_rain calls float
conditions calls cond_real, cond_integer, float
et_act calls amin1
nut_pminrl2 calls alog
nut_psed calls amin1
pl_graze calls amin1
salt_roadsalt calls float
swr_subwq calls hsc_d
hru_hyds calls min1, flow_hyd_ru_hru, float
salt_chem_hru calls nacl, activity_coefficient, caso4, caco3, cationexchange, 50, mgso4, ionic_strength, mgco3
surface calls ero_ysed, sq_volq, ero_eiusle, ero_pkq, sq_dailycn, sq_crackflow, ero_ovrsed, ero_cfactor
wetland_control calls conditions, res_sediment, wet_cs, res_nutrient, gwflow_wetl, res_hydro, wet_salt, ero_cfactor
nut_orgnc2 calls hsc_d
salt_rain calls float
mgt_operatn calls mgt_sched
swr_drains calls swr_depstor
pl_dormant calls amin1
wet_initial calls res_convert_mass
pl_burnop calls hrc_d, hpc_d, curno
sq_volq calls sq_greenampt, sq_daycn
pl_biomass_gro calls hpc_d, pl_tstr, cs_uptake, pl_nup, salt_uptake, pl_pup
pl_mortality calls amin1
mgt_newtillmix calls mgt_tillfactor
structure_set_parms calls ttcoef_wway
swr_satexcess calls amin1
mgt_harvbiomass calls hrc_d, hpc_d
res_nutrient calls amin1
pl_leaf_senes calls hrc_d, hpc_d, amin1
mgt_killop calls hrc_d, hpc_d, pl_rootfr
plant_init calls pl_seed_gro, pl_partition, amin1, pl_root_gro, float, xmon
pl_leaf_gro calls amin1, float, alog10
mgt_transplant calls pl_seed_gro, pl_partition, pl_root_gro, float
mgt_harvtuber calls pl_rootfr
mgt_sched calls pl_fert, mgt_newtillmix_wet, pl_burnop, mgt_newtillmix, mgt_harvresidue, pest_apply, mgt_harvbiomass, pl_fert_wet, mgt_killop, mgt_transplant, mgt_harvtuber, mgt_harvgrain, curno, salt_fert_wet, cs_fert_wet, mgt_plantop, cs_fert, salt_fert
pl_nut_demand calls pl_nupd, pl_pupd
pl_root_gro calls amin1, float
pl_waterup calls amin1, salt_chem_soil_single
cn2_init calls curno
mgt_harvgrain calls hpc_d
pl_tstr calls amin1
salt_chem_soil_single calls nacl, activity_coefficient, caso4, caco3, mgso4, ionic_strength, mgco3
pl_nup calls amin1, pl_nfix, nuts
pl_nupd calls float
pl_pup calls nuts
pl_pupd calls float
command calls hru_control
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq