hru_lte_read – SWAT+
hru_lte_read Subroutine
235 statements
Source File
subroutine hru_lte_read()
Uses
maximum_data_module
output_landscape_module
soil_data_module
conditional_module
climate_module
plant_data_module
hydrograph_module
hru_lte_module
input_file_module
time_module
dimension swatdeg output variables xwalk with soil_lte calculate shape parameters min to seconds
Arguments
None
Calls
Called by
Contents
None
Call graph
hru_lte_read calls amin1, ascrv
main calls hru_lte_read