hru_read – SWAT+
hru_read Subroutine
150 statements
Source File
subroutine hru_read()
Uses
landuse_data_module
maximum_data_module
hydrology_data_module
soil_data_module
constituent_mass_module
topography_data_module
hydrograph_module
input_file_module
hru_module
reservoir_data_module
Arguments
None
Calls
Called by
Contents
None
Call graph
hru_read calls allocate_parms
allocate_parms calls zero0, zero1, zero2, zeroini
proc_hru calls hru_read
main calls proc_hru