hyd_read_connect – SWAT+
hyd_read_connect Subroutine
290 statements
Source File
subroutine hyd_read_connect(con_file, obtyp, nspu1, nspu, nhyds, ndsave)
Uses
maximum_data_module
constituent_mass_module
climate_module
hydrograph_module
time_module
gwflow_module
read hru spatial data intialize area to calcluate drainage areas in hyd_connect set outflow object type to 0 - needed in final hyd_read_connect loop
Arguments
Type Intent Optional Attributes Name
character(len=20) :: con_file
character(len=8) :: obtyp
integer, intent(in) :: nspu1
integer, intent(in) :: nspu
integer, intent(in) :: nhyds
integer, intent(in) :: ndsave
Calls
Called by
Contents
None
Call graph
hyd_read_connect calls search
hyd_connect calls hyd_read_connect
main calls hyd_connect