hyd_connect – SWAT+
hyd_connect Subroutine
436 statements
Source File
subroutine hyd_connect()
Uses
ru_module
basin_module
recall_module
constituent_mass_module
hydrograph_module
input_file_module
organic_mineral_mass_module
gwflow_module
 ~ ~ ~ PURPOSE ~ ~ ~
 reads in the routing information from the watershed configuration
 input file (.fig) and calculates the number of subbasins, reaches,
 and reservoirs
set first object number of each type for each hru or defining unit, set all subbasins that contain it determine subbasin the hrus are in and add subbasin area to basin area only have hrus set up - need to add other objects determine number of recieving units and set object numbers for outflow hyds all channels receive flow from modflow allocate zero arrays for constituents allocate receiving arrays allocate unit hyd for all incoming hyd's loop through again and set receiving dependencies if modflow object and set for all channels set all incoming channel object data to modflow for subbasins, set receiving objects for each element (need for parallelization order) if routing over ru - the hru frac is included loop through again to set command (object) sequence calculate drainage area to compare to input area - need reservoir surface area add receiving object for single objects add subbasin elements modflow - for all inflow objects add recieving for all channels from modflow compute object order for parallelization (similar to stream order) compute object order of highest receiving object and add 1 subbasin has to be in parallel order after elements in the subbasin write calculated and input drainage areas for all objects except hru's
Arguments
None
Calls
Called by
Contents
None
Call graph
hyd_connect calls hyd_read_connect, gwflow_read, ru_read, recall_read, ru_read_elements, overbank_read, aqu2d_read, recall_read_salt, recall_read_cs, dr_db_read, gwflow_chan_read
hyd_read_connect calls search
gwflow_read calls 50, 10, 10000, 1000
ru_read_elements calls define_unit_elements
aqu2d_read calls define_unit_elements
dr_db_read calls dr_read_om, dr_path_read, dr_read_salt, dr_read_hmet, dr_read_pest
gwflow_chan_read calls 30
main calls hyd_connect