mallo_control – SWAT+
mallo_control Subroutine
51 statements
Source File
subroutine mallo_control(imallo)
Uses
basin_module
soil_module
plant_module
conditional_module
manure_allocation_module
time_module
organic_mineral_mass_module
hru_module
add manure produced on the first day of the month loop through each demand object for manure demand check decision table for manure application loop through each demand object again and subtract from source if available subtract manure from source set daily withdrawal and source
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: imallo
Calls
Called by
Contents
None
Call graph
mallo_control calls conditions, pl_fert, actions
conditions calls cond_real, cond_integer, float
actions calls pl_fert, mgt_newtillmix_wet, amax1, wet_initial, hru_lum_init, pl_burnop, mgt_newtillmix, mgt_harvresidue, pest_apply, structure_set_parms, mgt_harvbiomass, hru_fr_change, pl_fert_wet, mgt_killop, plant_init, amin1, mgt_transplant, mgt_harvtuber, pl_graze, cn2_init, mgt_harvgrain, curno
wet_initial calls res_convert_mass
pl_burnop calls curno, hpc_d, hrc_d
mgt_newtillmix calls mgt_tillfactor
structure_set_parms calls ttcoef_wway
mgt_harvbiomass calls hpc_d, hrc_d
mgt_killop calls hpc_d, hrc_d, pl_rootfr
plant_init calls amin1, float, xmon, pl_partition, pl_root_gro, pl_seed_gro
mgt_transplant calls float, pl_partition, pl_root_gro, pl_seed_gro
mgt_harvtuber calls pl_rootfr
pl_graze calls amin1
cn2_init calls curno
mgt_harvgrain calls hpc_d
pl_root_gro calls amin1, float
time_control calls mallo_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, calsoft_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq