mgt_harvresidue – SWAT+
mgt_harvresidue Subroutine
21 statements
Source File
subroutine mgt_harvresidue(jj, harveff)
Uses
organic_mineral_mass_module
plant_module
~ ~ ~ PURPOSE ~ ~ ~ this subroutine performs the harvest residue operation
~ ~ ~ INCOMING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
harvest each plant residue harvest total residue
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: jj
real, intent(in) :: harveff
Called by
Contents
None
Call graph
actions calls mgt_harvresidue
mgt_sched calls mgt_harvresidue
mallo_control calls actions
wallo_demand calls actions
sd_channel_control2 calls actions
sd_channel_control3 calls actions, wallo_control
time_control calls actions, mallo_control, wallo_control, command
hru_control calls actions, mgt_operatn
mgt_operatn calls mgt_sched
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, command, calsoft_control
wallo_control calls wallo_demand
command calls sd_channel_control2, sd_channel_control3, hru_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq