mgt_tillfactor – SWAT+
mgt_tillfactor Subroutine
44 statements
Source File
subroutine mgt_tillfactor(jj, bmix, emix, dtil)
Uses
soil_module
!!!!!!!!!!!!!!!!!!!!!
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: jj
real, intent(in) :: bmix
real :: emix
real :: dtil
Called by
Contents
None
Call graph
mgt_newtillmix calls mgt_tillfactor
actions calls mgt_newtillmix
mgt_sched calls mgt_newtillmix
time_control calls mgt_newtillmix, actions, mallo_control, wallo_control, command
mallo_control calls actions
wallo_demand calls actions
sd_channel_control2 calls actions
calsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
caltsoft_hyd calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, calsoft_control, command
sd_channel_control3 calls actions, wallo_control
hru_control calls actions, mgt_operatn
mgt_operatn calls mgt_sched
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
wallo_control calls wallo_demand
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq
calsoft_control calls calsoft_hyd, caltsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
command calls sd_channel_control2, sd_channel_control3, hru_control