mgt_newtillmix – SWAT+
mgt_newtillmix Subroutine
160 statements
Source File
subroutine mgt_newtillmix(jj, bmix, idtill)
Uses
basin_module
tillage_data_module
constituent_mass_module
soil_module
plant_module
organic_mineral_mass_module
hru_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine mixes residue and nutrients during tillage and
biological mixing
New version developed by Armen R. Kemanian in collaboration with Stefan Julich and Cole Rossi
Mixing was extended to all layers
A subroutine to simulate stimulation of organic matter decomposition was added
March 2009: testing has been minimal and further adjustments are expected
use with caution and report anomalous results to akemanian@brc.tamus.edu and jeff.arnold@usda.edu
~ ~ ~ INCOMING VARIABLES ~ ~ ~
name          |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
npmx          |none          |number of different pesticides used in the simulation
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~
Intrinsic: Min, Max
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
biological mixing tillage operation by zhang DSSAT tillage ======================= by zhang DSSAT tillage =======================
incorporate pathogens - no mixing - lost from transport incorporate pathogens incorporate fraction of residue in first and second layer stable humus pool msm = mass of soil mixed for the layer msn = mass of soil not mixed for the layer
calculate the mass each mixed element sand, silt and clay are % so take weighted ave by depth by zhang ============== by zhang
============= sand, silt and clay are % so divide by tillage depth by zhang ==============
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: jj
real, intent(in) :: bmix
integer, intent(in) :: idtill
Calls
Called by
Contents
None
Call graph
mgt_newtillmix calls mgt_tillfactor
actions calls mgt_newtillmix
mgt_sched calls mgt_newtillmix
time_control calls mgt_newtillmix, actions, mallo_control, wallo_control, command
mallo_control calls actions
wallo_demand calls actions
sd_channel_control2 calls actions
calsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
caltsoft_hyd calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, calsoft_control, command
sd_channel_control3 calls actions, wallo_control
hru_control calls actions, mgt_operatn
mgt_operatn calls mgt_sched
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
wallo_control calls wallo_demand
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq
calsoft_control calls calsoft_hyd, caltsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
command calls sd_channel_control2, sd_channel_control3, hru_control