mgt_operatn – SWAT+
mgt_operatn Subroutine
40 statements
Source File
subroutine mgt_operatn()
Uses
time_module
plant_module
mgt_operations_module
hru_module
~ ~ ~ PURPOSE ~ ~ ~ this subroutine performs all management operations
~ ~ ~ INCOMING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ daylmn(:) |hours |shortest daylength occurring during the |year dormhr(:) |hours |time threshold used to define dormant |period for plant (when daylength is within |the time specified by dormhr from the minimum |daylength for the area, the plant will go |dormant) phubase(:) |heat units |base zero total heat units (used when no |land cover is growing iop(:,:,:) |julian date |date of tillage operation phut(:,:,:) |none |fraction of heat units (base zero or plant) |at which tillage occurs ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~ SWAT: plantop, dormant, harvkillop, harvestop, killop, tillmix
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
Arguments
None
Calls
Called by
Contents
None
Call graph
mgt_operatn calls mgt_sched
mgt_sched calls mgt_harvresidue, salt_fert_wet, mgt_newtillmix, mgt_killop, pl_fert_wet, cs_fert_wet, salt_fert, pest_apply, mgt_newtillmix_wet, mgt_plantop, mgt_transplant, mgt_harvgrain, mgt_harvbiomass, mgt_harvtuber, pl_fert, cs_fert, curno, pl_burnop
mgt_newtillmix calls mgt_tillfactor
mgt_killop calls hpc_d, hrc_d, pl_rootfr
mgt_transplant calls pl_partition, pl_root_gro, float, pl_seed_gro
mgt_harvgrain calls hpc_d
mgt_harvbiomass calls hpc_d, hrc_d
mgt_harvtuber calls pl_rootfr
pl_burnop calls curno, hpc_d, hrc_d
pl_root_gro calls float, amin1
hru_control calls mgt_operatn
command calls hru_control
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq