mgt_sched – SWAT+
mgt_sched Subroutine
389 statements
Source File
subroutine mgt_sched(isched)
Uses
basin_module
maximum_data_module
tillage_data_module
calibration_data_module
constituent_mass_module
soil_module
plant_module
plant_data_module
hydrograph_module
time_module
organic_mineral_mass_module
aquifer_module
hru_module
reservoir_module
reservoir_data_module
mgt_operations_module
plant one plant or entire community check to see if the crop is already growing plant if the crop is not growing don't plant if the crop is already growing begin and end monsoon initiation period if precip/pet ratio was not triggered during monsoon season - reset phenology harvest only operation sum yield and number of harvest to calc ave yields sum basin crop yields and area harvested sum regional crop yields for soft calibration kill operation harvest and kill operation sum yield and num. of harvest to calc ave yields sum basin crop yields and area harvested sum regional crop yields for soft calibration tillage operation date scheduled irrigation operation fertilizer operation pesticide operation
grazing operation fertilizer operation burning street sweeping (only if iurban=2) set drain depth for drainage water management added below changed plcur(ipl) to plcur(j) and plm(ipl) to plm(j) gsm 1/30/2018 set/adjust weir height
set weir height and adjust principal spillway storage and depth continuous irrigation to maintain surface ponding in rice fields Jaehak 2022 date scheduled irrigation operation for rice fields Puddling operation Jaehak 2022 xwalk with puddling ops names skip a year
Arguments
Type Intent Optional Attributes Name
integer :: isched
Calls
Called by
Contents
None
Call graph
mgt_sched calls mgt_harvresidue, salt_fert_wet, mgt_newtillmix, mgt_killop, pl_fert_wet, cs_fert_wet, salt_fert, pest_apply, mgt_newtillmix_wet, mgt_plantop, mgt_transplant, mgt_harvgrain, mgt_harvbiomass, mgt_harvtuber, pl_fert, cs_fert, curno, pl_burnop
mgt_newtillmix calls mgt_tillfactor
mgt_killop calls hpc_d, hrc_d, pl_rootfr
mgt_transplant calls pl_partition, pl_root_gro, float, pl_seed_gro
mgt_harvgrain calls hpc_d
mgt_harvbiomass calls hpc_d, hrc_d
mgt_harvtuber calls pl_rootfr
pl_burnop calls curno, hpc_d, hrc_d
pl_root_gro calls float, amin1
mgt_operatn calls mgt_sched
hru_control calls mgt_operatn
command calls hru_control
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq