overbank_read – SWAT+
overbank_read Subroutine
64 statements
Source File
subroutine overbank_read()
Uses
hydrograph_module
input_file_module
maximum_data_module
sd_channel_module
read data for surface elements in the floodplain-for overbank flooding
Arguments
None
Called by
Contents
None
Call graph
proc_cha calls overbank_read
hyd_connect calls overbank_read
main calls proc_cha, hyd_connect