pl_biomass_gro – SWAT+
pl_biomass_gro Subroutine
96 statements
Source File
subroutine pl_biomass_gro()
Uses
basin_module
constituent_mass_module
plant_module
climate_module
plant_data_module
salt_data_module
hydrograph_module
salt_module
organic_mineral_mass_module
carbon_module
hru_module
if plant hasn't reached maturity calculate optimal biomass adjust radiation-use efficiency for CO2 adjust radiation-use efficiency for vapor pressure deficit assumes vapor pressure threshold of 1.0 kPa adjust radiation-use efficiency for day length compute temperature stress
compute n and p uptake and stresses try water stress as function of precip/pet
code to turn off all plant stress code to turn off nutrient plant stress only reduce predicted biomass due to stress on plant reduce predicted biomass due to salt stress on plant (rtb salt) increase in plant c sum plant stresses
Arguments
None
Calls
Called by
Contents
None
Call graph
pl_biomass_gro calls pl_tstr, hpc_d, pl_pup, pl_nup, cs_uptake, salt_uptake
pl_tstr calls amin1
pl_pup calls nuts
pl_nup calls amin1, nuts, pl_nfix
pl_grow calls pl_biomass_gro
hru_control calls pl_grow
command calls hru_control
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq