pl_community – SWAT+
pl_community Subroutine
120 statements
Source File
subroutine pl_community()
Uses
soil_module
plant_module
climate_module
plant_data_module
organic_mineral_mass_module
time_module
hru_module
~ ~ ~ PURPOSE ~ ~ ~ this subroutine predicts daily potential growth of total plant biomass and roots and calculates leaf area index. Incorporates residue for tillage functions and decays residue on ground surface. Adjusts daily dry matter based on water stress.
~ ~ ~ INCOMING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ phubase(:) |heat units |base zero total heat units (used when no |land cover is growing) phutot(:) |heat units |total potential heat units for year (used |when no crop is growing) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ phubase(:) |heat units |base zero total heat units (used when no |land cover is growing) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~ Intrinsic: Max SWAT: operatn, swu, grow
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
calc total lai for plant community calc max water uptake for each plant sum total masses for plant community calc max height for penman pet equation calc total biomass for plant community
check to see if inter row cropping or competition for light (canopy shadowing) calculate photosynthetically active radiation for each plant competition for light calculate photosynthetically active radiation during growth period calculate photosynthetically active radiation for one plant calculate photosynthetically active radiation for multiple plants
Arguments
None
Calls
Called by
Contents
None
Call graph
pl_community calls pl_waterup
pl_waterup calls amin1, salt_chem_soil_single
salt_chem_soil_single calls ionic_strength, nacl, caco3, caso4, activity_coefficient, mgco3, mgso4
hru_control calls pl_community
command calls hru_control
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq