pl_fert_wet – SWAT+
pl_fert_wet Subroutine
40 statements
Source File
subroutine pl_fert_wet(ifrt, frt_kg)
Uses
fertilizer_data_module
basin_module
hydrograph_module
organic_mineral_mass_module
hru_module
mgt_operations_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine applies N and P specified by date and
amount in the management file (.mgt) for rice fields during ponding periods
Jaehak 2022
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~
SWAT: Erfc
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
added by zhang
summary calculations
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ifrt
real, intent(in) :: frt_kg
added by zhang
Called by
Contents
None
Call graph
actions calls pl_fert_wet
mgt_sched calls pl_fert_wet
mallo_control calls actions
wallo_demand calls actions
sd_channel_control2 calls actions
sd_channel_control3 calls actions, wallo_control
time_control calls actions, mallo_control, wallo_control, command
hru_control calls actions, mgt_operatn
mgt_operatn calls mgt_sched
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, command, calsoft_control
wallo_control calls wallo_demand
command calls sd_channel_control2, sd_channel_control3, hru_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq