pl_fert – SWAT+
pl_fert Subroutine
89 statements
Source File
subroutine pl_fert(ifrt, frt_kg, fertop)
Uses
fertilizer_data_module
basin_module
organic_mineral_mass_module
hru_module
mgt_operations_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine applies N and P specified by date and
amount in the management file (.mgt)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~
SWAT: Erfc
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
added by zhang
By Zhang for C/N cycling
Allocate organic fertilizer to Slow (SWAT_active) N pool; remaining organic N is llocated to structural litter N pool By Zhang for C/N cycling ===========================
summary calculations
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ifrt
real, intent(in) :: frt_kg
integer, intent(in) :: fertop
Called by
Contents
None
Call graph
actions calls pl_fert
hru_control calls pl_fert, actions, mgt_operatn
mgt_sched calls pl_fert
mallo_control calls pl_fert, actions
wallo_demand calls actions
sd_channel_control2 calls actions
sd_channel_control3 calls actions, wallo_control
command calls hru_control, sd_channel_control2, sd_channel_control3
time_control calls actions, mallo_control, command, wallo_control
mgt_operatn calls mgt_sched
caltsoft_hyd calls time_control
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
wallo_control calls wallo_demand
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq