pl_graze – SWAT+
pl_graze Subroutine
134 statements
Source File
subroutine pl_graze()
Uses
fertilizer_data_module
basin_module
soil_module
plant_module
organic_mineral_mass_module
hru_module
carbon_module
mgt_operations_module
graze only if adequate biomass in HRU set initial biomass before eating and trampling remove biomass eaten - assume evenly divided by biomass of plant later we can add preferences - by animal type or simply by n and p content remove biomass and organics from plant pools update remaining plant organic pools remove biomass trampled - assume evenly divided by biomass of plant remove biomass and organics from plant pools update remaining plant organic pools reset leaf area index and fraction of growing season assume lai doesn't start decreasing until 2,500 kg/ha at 1.0 lai per 1000 kg/ha plant loop
apply manure By Zhang for C/N cycling ===============================
Arguments
None
Calls
Called by
Contents
None
Call graph
pl_graze calls amin1
actions calls pl_graze
hru_control calls pl_graze, actions
mallo_control calls actions
wallo_demand calls actions
sd_channel_control2 calls actions
sd_channel_control3 calls actions, wallo_control
time_control calls actions, mallo_control, command, wallo_control
command calls hru_control, sd_channel_control2, sd_channel_control3
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, command, calhard_control, calsoft_control
wallo_control calls wallo_demand
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq