pl_partition – SWAT+
pl_partition Subroutine
113 statements
Source File
subroutine pl_partition(j)
Uses
basin_module
plant_module
plant_data_module
organic_mineral_mass_module
carbon_module
hru_module
update plant mass for daily biomass/c increase partition leaf and stem (stalk) and seed (grain) mass partition root and above ground biomass for tuber crops for tubers, the tuber (or seed) is not part of ab_gr --> tot = root + ab_gr + seed 1. = root + ab_gr + hi * ab_gr --> solve for ab_gr partition root and above ground biomass for all other annuals (above ground grain) partition carbon with constant fractions partition n and p partition leaves and seed (stem is woody biomass) if n is neg after seed is removed - assume 0 n in seed - plant database cnyld and fr_n_mat are off partition n_left between remaining masses - assume equal concentrations if n is neg after seed is removed - assume 0 n in seed - plant database cnyld and fr_n_mat are off partition p_left between remaining masses - assume equal concentrations annual or grass (stem is stalk) - partition seed (grain) assume same concentration in rest of plant assume same concentration in rest of plant
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: j
Called by
Contents
None
Call graph
mgt_transplant calls pl_partition
pl_grow calls pl_partition
plant_init calls pl_partition
actions calls mgt_transplant, plant_init
plant_all_init calls plant_init
mgt_sched calls mgt_transplant
hru_control calls pl_grow, actions, mgt_operatn
mallo_control calls actions
wallo_demand calls actions
sd_channel_control2 calls actions
sd_channel_control3 calls actions, wallo_control
time_control calls actions, mallo_control, command, wallo_control
proc_hru calls plant_all_init
mgt_operatn calls mgt_sched
command calls hru_control, sd_channel_control2, sd_channel_control3
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, proc_hru, command, calhard_control, calsoft_control
wallo_control calls wallo_demand
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq