pl_pupd – SWAT+
pl_pupd Subroutine
27 statements
Source File
subroutine pl_pupd()
Uses
organic_mineral_mass_module
plant_module
hru_module
plant_data_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine calculates plant phosphorus demand
~ ~ ~ INCOMING VARIABLES ~ ~ ~
name        |units          |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
bio_p1(:)   |none           |1st shape parameter for plant P uptake
                            |equation
bio_p2(:)   |none           |2st shape parameter for plant P uptake
                            |equation
ihru        |none           |HRU number
                            |fraction of P in crop biomass at maturity
~ ~ ~ OUTGOING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
icrop       |none          |land cover code
j           |none          |HRU number
uapd        |kg P/ha       |plant demand of phosphorus
up2         |kg P/ha       |optimal plant phosphorus content
upmx        |kg P/ha       |maximum amount of phosphorus that can be
                           |removed from the soil layer
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~
Intrinsic: Exp, Min
SWAT: nuts
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
set fraction to maturity for annuals and perennials luxury p uptake
**jga luxury p uptake
Arguments
None
Calls
Called by
Contents
None
Call graph
pl_pupd calls float
pl_nut_demand calls pl_pupd
pl_grow calls pl_nut_demand
hru_control calls pl_grow
command calls hru_control
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq