pl_rootfr – SWAT+
pl_rootfr Subroutine
68 statements
Source File
subroutine pl_rootfr()
Uses
soil_module
plant_module
hru_module
This subroutine distributes dead root mass through the soil profile code developed by Armen R. Kemanian in 2008 March, 2009 further adjustments expected
 ensures that cumulative fractional root distribution = 1
Arguments
None
Called by
Contents
None
Call graph
mgt_harvtuber calls pl_rootfr
mgt_killop calls pl_rootfr
actions calls mgt_harvtuber, mgt_killop
mgt_sched calls mgt_harvtuber, mgt_killop
mallo_control calls actions
wallo_demand calls actions
sd_channel_control2 calls actions
sd_channel_control3 calls actions, wallo_control
time_control calls actions, mallo_control, wallo_control, command
hru_control calls actions, mgt_operatn
mgt_operatn calls mgt_sched
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, command, calsoft_control
wallo_control calls wallo_demand
command calls sd_channel_control2, sd_channel_control3, hru_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq