pl_waterup – SWAT+
pl_waterup Subroutine
134 statements
Source File
subroutine pl_waterup()
Uses
basin_module
constituent_mass_module
soil_module
urban_data_module
plant_module
plant_data_module
salt_data_module
hru_module
~ ~ ~ PURPOSE ~ ~ ~ this subroutine distributes potential plant evaporation through the root zone and calculates actual plant water use based on soil water availability. Also estimates water stress factor.
~ ~ ~ INCOMING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ epco(:) |none |plant water uptake compensation factor (0-1) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ep_day |mm H2O |actual amount of transpiration that occurs |on day in HRU ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ gx | ir | j |none |HRU number k |none |counter (soil layer) reduc |none |fraction of water uptake by plants achieved |where the reduction is caused by low water |content sum | sump | wuse |mm H2O |water uptake by plants in each soil layer sum_wuse |mm H2O |water uptake by plants from all layers ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~ Intrinsic: Exp, Max
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
compute aeration stress compute limiting water stress initialize variables let second layer compensate - 10 mm layer causes problems wehn root depth is shallow soil layer loop
update total soil water in profile
Arguments
None
Calls
Called by
Contents
None
Call graph
pl_waterup calls amin1, salt_chem_soil_single
salt_chem_soil_single calls ionic_strength, nacl, caco3, caso4, activity_coefficient, mgco3, mgso4
pl_community calls pl_waterup
hru_control calls pl_community
command calls hru_control
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq