pl_write_parms_cal – SWAT+
pl_write_parms_cal Subroutine
49 statements
Source File
subroutine pl_write_parms_cal()
Uses
maximum_data_module
calibration_data_module
plant_module
hydrograph_module
input_file_module
read landscape soft calibration data for each land use and parameter write parameters to file
Arguments
None
Calls
Called by
Contents
None
Call graph
pl_write_parms_cal calls amin1
calsoft_control calls pl_write_parms_cal
main calls calsoft_control