plant_init – SWAT+
plant_init Subroutine
309 statements
Source File
subroutine plant_init(init, iihru)
Uses
maximum_data_module
landuse_data_module
soil_module
urban_data_module
plant_module
climate_module
conditional_module
plant_data_module
hydrograph_module
time_module
organic_mineral_mass_module
hru_module
mgt_operations_module
allocate plants allocate water uptake by layer start accumulating hu at end of dormancy (daylength) calculate solar declination: equation 2.1.2 in SWAT manual 365/2pi = 58.09 calculate the relative distance of the earth from the sun the eccentricity of the orbit sdlat will be >= 1. if latitude exceeds +/- 66.5 deg in winter latitude exceeds +/- 66.5 deg in summer set fraction to maturity and initial canopy height for annuals and perennials set intial n and p contents in total plant initialize plant mass if plant growing get average residue cover factor for community set epco parameter for each crop set p factor and slope length (ls factor) xwalk urban land use type with urban name in urban.urb xwalk overland n with name in ovn_table.lum
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: init
integer, intent(in) :: iihru
Calls
Called by
Contents
None
Call graph
plant_init calls xmon, pl_partition, pl_root_gro, pl_seed_gro, float, amin1
pl_root_gro calls float, amin1
actions calls plant_init
plant_all_init calls plant_init
mallo_control calls actions
wallo_demand calls actions
sd_channel_control2 calls actions
sd_channel_control3 calls actions, wallo_control
time_control calls actions, mallo_control, wallo_control, command
hru_control calls actions
proc_hru calls plant_all_init
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, proc_hru, calhard_control, command, calsoft_control
wallo_control calls wallo_demand
command calls sd_channel_control2, sd_channel_control3, hru_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq