plant_all_init – SWAT+
plant_all_init Subroutine
55 statements
Source File
subroutine plant_all_init()
Uses
maximum_data_module
plant_module
plant_data_module
hydrograph_module
hru_module
assign land use pointers for the hru allocate and initialize land use and management ihru, ilu and isol are in modparm find all different plants in simulation for yield output set all plants simulated in the basin zero basin crop yields and harvested areas
Arguments
None
Calls
Called by
Contents
None
Call graph
plant_all_init calls plant_init
plant_init calls xmon, pl_partition, pl_root_gro, pl_seed_gro, float, amin1
pl_root_gro calls float, amin1
proc_hru calls plant_all_init
main calls proc_hru