proc_read – SWAT+
proc_read Subroutine
39 statements
Source File
subroutine proc_read()
read pesticide metabolites
Arguments
None
Calls
Called by
Contents
None
Call graph
proc_read calls soil_plant_init, pest_hru_aqu_read, cs_uptake_read, cli_read_atmodep_salt, path_hru_aqu_read, cli_read_atmodep_cs, snowdb_read, ch_read_temp, constit_db_read, salt_irr_read, cs_reactions_read, topo_read, salt_hru_read, salt_urban_read, cs_irr_read, cs_plant_read, cs_urban_read, soil_plant_init_cs, salt_roadsalt_read, cs_aqu_read, field_read, hydrol_read, cli_read_atmodep, solt_db_read, salt_plant_read, soil_lte_db_read, salt_aqu_read, salt_uptake_read, cs_hru_read, soil_db_read, cli_staread, pest_metabolite_read, hmet_hru_aqu_read, salt_fert_read, cs_fert_read
cli_staread calls search
main calls proc_read