proc_cha – SWAT+
proc_cha Subroutine
29 statements
Source File
subroutine proc_cha()
Uses
hydrograph_module
intialize stream-aquifer interactions for geomorphic baseflow aquifer to channel flow initialize flow routing variables
Arguments
None
Calls
Called by
Contents
None
Call graph
proc_cha calls ch_read_init, ch_read_sed, sd_channel_read, ch_read_nut, sd_hydsed_read, ch_ttcoef, ch_initial, sd_channel_surf_link, ch_read_hyd, ch_read_init_cs, ch_read, sd_hydsed_init, aqu2d_init, overbank_read, time_conc_init
main calls proc_cha