proc_hru – SWAT+
proc_hru Subroutine
52 statements
Source File
subroutine proc_hru()
Uses
maximum_data_module
landuse_data_module
constituent_mass_module
soil_module
erosion_module
hydrograph_module
hru_module
septic has to be set before soils are initialized (making a soil layer for the septic zone) allocate erosion output and open file !!! new checker.out file - always prints !!! new checker.out file - always prints
Arguments
None
Calls
Called by
Contents
None
Call graph
proc_hru calls hru_read, topohyd_init, structure_set_parms, hru_output_allo, soils_init, plant_all_init, hydro_init, pesticide_init, salt_hru_init, rte_read_nut, hru_allo, hru_lum_init_all, hrudb_init, carbon_read, structure_init, cn2_init_all, pathogen_init, cs_hru_init
hru_read calls allocate_parms
topohyd_init calls ascrv, amin1
structure_set_parms calls ttcoef_wway
hru_output_allo calls hrc_d, hscf_d, hrc_a, hscf_a, hsc_y, hpc_y, hrc_m, hscf_m, hsc_d, hpc_d, hsc_a, hpc_a, hrc_y, hscf_y, hsc_m, hpc_m
soils_init calls soil_phys_init, layersplit
plant_all_init calls plant_init
hru_lum_init_all calls hru_lum_init
structure_init calls structure_set_parms
cn2_init_all calls cn2_init
plant_init calls amin1, xmon, pl_partition, pl_root_gro, pl_seed_gro, float
allocate_parms calls zero0, zero2, zero1, zeroini
cn2_init calls curno
pl_root_gro calls amin1, float
main calls proc_hru