proc_res – SWAT+
proc_res Subroutine
19 statements
Source File
subroutine proc_res()
Uses
hydrograph_module
allocate and initialize reservoir variables Osvaldo
Arguments
None
Calls
Called by
Contents
None
Call graph
proc_res calls res_read_hyd, res_read_csdb, res_objects, res_read_init, res_read_conds, res_read, res_initial, res_read_sed, res_read_nut, res_read_saltdb, res_allo, res_read_salt_cs
res_initial calls res_convert_mass
main calls proc_res