proc_open – SWAT+
proc_open Subroutine
21 statements
Source File
subroutine proc_open()
write headers in output files
Arguments
None
Calls
Called by
Contents
None
Call graph
proc_open calls header_sd_channel, header_lu_change, header_aquifer, header_hyd, header_snutc, header_water_allocation, header_path, header_salt, output_landscape_init, header_channel, header_mgt, header_yield, header_reservoir, header_wetland, header_pest, header_const, header_write
main calls proc_open