proc_bsn – SWAT+
proc_bsn Subroutine
19 statements
Source File
subroutine proc_bsn()
Uses
time_module
! open file to print all output files that are written ! open diagnostics.out file to print problems with various files ext to 8000 recl per email 8/2/21 - Kai-Uwe ! open drainage areas output file
Arguments
None
Calls
Called by
Contents
None
Call graph
proc_bsn calls time_read, basin_print_codes_read, co2_read, basin_prm_default, basin_read_cc, basin_read_prm, basin_read_objs, readcio_read
time_read calls xmon
main calls proc_bsn