proc_cal – SWAT+
proc_cal Subroutine
21 statements
Source File
subroutine proc_cal()
Uses
hydrograph_module
calibration_data_module
need to read plant parms before calibrating read soft calibration parameters
Arguments
None
Calls
Called by
Contents
None
Call graph
proc_cal calls cal_parm_read, calsoft_read_codes, cal_parmchg_read, lcu_read_softcal, pl_read_regions_cal, aqu_read_elements, res_read_elements, ch_read_orders_cal, cal_allo_init, pl_read_parms_cal, cal_conditions, ls_read_lsparms_cal, ch_read_elements, rec_read_elements, ch_read_parms_cal
cal_parmchg_read calls define_unit_elements
pl_read_regions_cal calls define_unit_elements
aqu_read_elements calls define_unit_elements
res_read_elements calls define_unit_elements
pl_read_parms_cal calls define_unit_elements
cal_conditions calls cal_parm_select
ch_read_elements calls define_unit_elements
rec_read_elements calls define_unit_elements
cal_parm_select calls curno, amin1, soil_text_init, soil_awc_init
main calls proc_cal