proc_db – SWAT+
proc_db Subroutine
31 statements
Source File
subroutine proc_db()
databases used by all spatial modules read the plant paramter database initialize plant parameters read plant transplant data read the tillage database read the pesticide database read the fertilizer/nutrient database read the urban land types database read the pathogen data parameters read management scheduling and data files
read structural operations files read the plant community database
Arguments
None
Calls
Called by
Contents
None
Call graph
proc_db calls plantparm_init, mgt_read_grazeops, scen_read_grwway, sep_read, mgt_read_chemapp, sdr_read, overland_n_read, mgt_read_mgtops, cntbl_read, plant_transplant_read, till_parm_read, scen_read_bmpuser, cons_prac_read, path_parm_read, mgt_read_sweepops, landuse_read, mgt_read_harvops, urban_parm_read, mgt_read_irrops, mgt_read_puddle, scen_read_filtstrip, pest_parm_read, readpcom, plant_parm_read, fert_parm_read, septic_parm_read, mgt_read_fireops
plantparm_init calls ascrv
mgt_read_mgtops calls read_mgtops
main calls proc_db