proc_date_time – SWAT+
proc_date_time Subroutine
42 statements
Source File
subroutine proc_date_time()
Uses
time_module
Arguments
None
Calls
Called by
Contents
None
Call graph
proc_date_time calls cli_pmeas, cli_wgnread, cli_wmeas, cli_smeas, cli_petmeas, cli_hmeas, cli_tmeas
cli_wgnread calls gcycl, cli_initwgn
cli_tmeas calls xmon
main calls proc_date_time