rcurv_interp_flo – SWAT+
rcurv_interp_flo Subroutine
30 statements
Source File
subroutine rcurv_interp_flo(icha, flo_rate)
Uses
sd_channel_module
~ ~ ~ PURPOSE ~ ~ ~ this subroutine interpolates between points on a rating curve given flow rate
keep max travel time at max bankfull
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: icha
real, intent(in) :: flo_rate
Calls
Called by
Contents
None
Call graph
rcurv_interp_flo calls chrc_interp
ch_rtmusk calls rcurv_interp_flo
sd_channel_sediment3 calls rcurv_interp_flo
sd_channel_control3 calls ch_rtmusk, sd_channel_sediment3
channel_control calls ch_rtmusk
sd_channel_control2 calls ch_rtmusk
command calls sd_channel_control3, sd_channel_control2
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq