read_mgtops – SWAT+
read_mgtops Subroutine
128 statements
Source File
subroutine read_mgtops(isched)
Uses
fertilizer_data_module
pesticide_data_module
maximum_data_module
tillage_data_module
plant_data_module
time_module
mgt_operations_module
operation loop operation character operation type character plant character override
xwalk with transplant data file herehere no null operation loop
Arguments
Type Intent Optional Attributes Name
integer :: isched
Called by
Contents
None
Call graph
mgt_read_mgtops calls read_mgtops
proc_db calls mgt_read_mgtops
main calls proc_db