rec_read_elements – SWAT+
rec_read_elements Subroutine
145 statements
Source File
subroutine rec_read_elements()
Uses
hydrograph_module
input_file_module
maximum_data_module
calibration_data_module
allocate recall outputsby region all hrus are in region setting up regions for recall soft cal and/or output by type all hrus are in region if no regions are input, don"t need elements read data for each element in all landscape cataloging units
Arguments
None
Calls
Called by
Contents
None
Call graph
rec_read_elements calls define_unit_elements
proc_cal calls rec_read_elements
main calls proc_cal