res_hydro – SWAT+
res_hydro Subroutine
145 statements
Source File
subroutine res_hydro(jres, id, pvol_m3, evol_m3)
Uses
water_allocation_module
soil_module
water_body_module
conditional_module
climate_module
hydrograph_module
time_module
hru_module
reservoir_module
reservoir_data_module
release at constant rate release at percentage of principal volume JK: added functionality to use const2 to reduce/increase inflow variable - const is max release release at fraction of inflow release all volume above emergency release based on drawdown days release based on drawdown days + percentage of principal volume release inflow + all volume over target (pvol_m3), use condition associated with action release based on irrigation demand of hru or water rights object const allows a fraction (usually > 1.0) of the demand (m3) released release based on weir equation measured outflow or release
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: jres
integer, intent(in) :: id
real, intent(in) :: pvol_m3
real, intent(in) :: evol_m3
Called by
Contents
None
Call graph
wetland_control calls res_hydro
res_control calls res_hydro
hru_control calls wetland_control
command calls res_control, hru_control
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq