res_read_elements – SWAT+
res_read_elements Subroutine
140 statements
Source File
subroutine res_read_elements()
Uses
maximum_data_module
calibration_data_module
hydrograph_module
input_file_module
reservoir_module
all hrus are in region setting up regions for reservoir soft cal and/or output by type all hrus are in region if no regions are input, don"t need elements read data for each element in all landscape cataloging units
Arguments
None
Calls
Called by
Contents
None
Call graph
res_read_elements calls define_unit_elements
proc_cal calls res_read_elements
main calls proc_cal