ru_read_elements – SWAT+
ru_read_elements Subroutine
159 statements
Source File
subroutine ru_read_elements()
Uses
hydrograph_module
dr_module
input_file_module
maximum_data_module
read data for each element in all subbasins dr_om_num was previously xwalked with dr_db()%om_file read subbasin definition data -ie. hru"s in the subbasin Linux initialization issue (Srin)
Arguments
None
Calls
Called by
Contents
None
Call graph
ru_read_elements calls define_unit_elements
hyd_connect calls ru_read_elements
main calls hyd_connect