salt_irrig – SWAT+
salt_irrig Subroutine
154 statements
Source File
subroutine salt_irrig(iwallo, idmd, ihru)
Uses
basin_module
salt_aquifer
water_allocation_module
constituent_mass_module
water_body_module
hydrograph_module
salt_module
ch_salt_module
hru_module
reservoir_data_module
aquifer_module
res_salt_module
~ ~ ~ PURPOSE ~ ~ ~ this subroutine adds salt mass from irrigation water into the soil profile, and removes salt mass from the source object
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: iwallo
integer, intent(inout) :: idmd
integer, intent(inout) :: ihru
Called by
Contents
None
Call graph
wallo_control calls salt_irrig
sd_channel_control3 calls wallo_control
time_control calls wallo_control, command
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, command, calsoft_control
command calls sd_channel_control3
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq