salt_chem_hru – SWAT+
salt_chem_hru Subroutine
217 statements
Source File
subroutine salt_chem_hru()
Uses
basin_module
constituent_mass_module
soil_module
salt_data_module
salt_module
time_module
hru_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine calculates salt ion concentrations based on equilibrium chemical reactions, for an HRU
(precipitation-dissolution, complexation, cation exchange)
~ ~ ~ INCOMING VARIABLES ~ ~ ~
name          |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
ihru          |none          |HRU number
sol_csalt     |mg Salt/L     |concentration of salt ions in solution in each soil layer
saltgw_conc   !mg Salt/L     |concentration of salt ions in groundwater
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~
name          |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
sol_csalt     |mg Salt/L     |concentration of salt ions in solution in each soil layer
saltgw_conc   !mg Salt/L     |concentration of salt ions in groundwater
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
*** End Precipitation-Dissolution Package *****
Arguments
None
Calls
Called by
Contents
None
Call graph
salt_chem_hru calls ionic_strength, nacl, caco3, cationexchange, caso4, 50, activity_coefficient, mgco3, mgso4
hru_control calls salt_chem_hru
command calls hru_control
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq