sd_channel_control2 – SWAT+
sd_channel_control2 Subroutine
90 statements
Source File
subroutine sd_channel_control2()
Uses
channel_module
constituent_mass_module
channel_data_module
conditional_module
climate_module
sd_channel_module
ch_pesticide_module
hydrograph_module
set ht1 to incoming daily hydrograph if connected to aquifer - add flow set inflow hyds for printing zero outgoing flow and sediment - ht2 use modified qual-2e routines don't route constituents if flow is zero convert mass to concentration compute max flow depth and corresponding travel time during day convert concentration to mass route constituents call mike winchell's new routine for pesticide routing
route pathogens check decision table for flow control - water allocation output channel organic-mineral output flow to channel morphology set pesticide output variables
Arguments
None
Calls
Called by
Contents
None
Call graph
sd_channel_control2 calls ch_rtmusk, hyd_convert_mass_to_conc, conditions, actions, ch_rtpath, sd_channel_sediment, hyd_convert_conc_to_mass, ch_watqual4, ch_rtpest
ch_rtmusk calls rcurv_interp_flo
conditions calls cond_real, cond_integer, float
actions calls mgt_newtillmix_wet, amax1, wet_initial, hru_lum_init, pl_burnop, mgt_newtillmix, mgt_harvresidue, pest_apply, structure_set_parms, mgt_harvbiomass, hru_fr_change, pl_fert_wet, mgt_killop, plant_init, amin1, mgt_transplant, mgt_harvtuber, pl_graze, cn2_init, pl_fert, mgt_harvgrain, curno
ch_rtpath calls theta
ch_watqual4 calls amin1
rcurv_interp_flo calls chrc_interp
wet_initial calls res_convert_mass
pl_burnop calls curno, hpc_d, hrc_d
mgt_newtillmix calls mgt_tillfactor
structure_set_parms calls ttcoef_wway
mgt_harvbiomass calls hpc_d, hrc_d
mgt_killop calls hpc_d, hrc_d, pl_rootfr
plant_init calls amin1, float, xmon, pl_partition, pl_root_gro, pl_seed_gro
mgt_transplant calls float, pl_partition, pl_root_gro, pl_seed_gro
mgt_harvtuber calls pl_rootfr
pl_graze calls amin1
cn2_init calls curno
mgt_harvgrain calls hpc_d
pl_root_gro calls amin1, float
command calls sd_channel_control2
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq