sd_channel_control3 – SWAT+
sd_channel_control3 Subroutine
346 statements
Source File
subroutine sd_channel_control3()
Uses
channel_module
basin_module
water_allocation_module
constituent_mass_module
water_body_module
channel_data_module
conditional_module
climate_module
channel_velocity_module
sd_channel_module
ch_pesticide_module
hydrograph_module
ch_salt_module
time_module
ch_cs_module
gwflow_module
! nbs added 7-20-23 set ht1 to incoming hydrograph set outgoing flow and sediment - ht2 add water transfer adjust precip and temperature for elevation using lapse rates if connected to aquifer - add flow set inflow hyds for printing zero outgoing flow and sediment - ht2 route constituents call mike winchell's new routine for pesticide routing
subtract evaporation total outgoing to output to SWIFT travel time > timestep -- then all incoming is stored and frac of stored is routed travel time < timestep -- route all stored and frac of incoming check decision table for flow control - water diversion check decision table for water allocation set outflow hyd to ht2 after diverting water calculate stream temperature set constituents for routing output channel organic-mineral output channel morphology set pesticide output variables set values for recharge hydrograph - should be trans losses
Arguments
None
Calls
Called by
Contents
None
Call graph
sd_channel_control3 calls gwflow_gwsw, ch_rtmusk, ch_rtpath, conditions, gwflow_tile, actions, cli_lapse, gwflow_satx, gwflow_canl, sd_channel_sediment3, ch_rtpest, wallo_control
ch_rtmusk calls rcurv_interp_flo
ch_rtpath calls theta
conditions calls cond_real, cond_integer, float
actions calls mgt_newtillmix_wet, amax1, wet_initial, hru_lum_init, pl_burnop, mgt_newtillmix, mgt_harvresidue, pest_apply, structure_set_parms, mgt_harvbiomass, hru_fr_change, pl_fert_wet, mgt_killop, plant_init, amin1, mgt_transplant, mgt_harvtuber, pl_graze, cn2_init, pl_fert, mgt_harvgrain, curno
sd_channel_sediment3 calls rcurv_interp_flo, amax1
wallo_control calls wallo_demand, wallo_transfer, wallo_withdraw, wallo_treatment, salt_irrig, cs_irrig
rcurv_interp_flo calls chrc_interp
wallo_demand calls conditions, actions
wet_initial calls res_convert_mass
pl_burnop calls curno, hpc_d, hrc_d
mgt_newtillmix calls mgt_tillfactor
structure_set_parms calls ttcoef_wway
mgt_harvbiomass calls hpc_d, hrc_d
wallo_withdraw calls gwflow_ppag
mgt_killop calls hpc_d, hrc_d, pl_rootfr
plant_init calls amin1, float, xmon, pl_partition, pl_root_gro, pl_seed_gro
mgt_transplant calls float, pl_partition, pl_root_gro, pl_seed_gro
mgt_harvtuber calls pl_rootfr
pl_graze calls amin1
wallo_treatment calls hyd_convert_conc_to_mass
cn2_init calls curno
mgt_harvgrain calls hpc_d
pl_root_gro calls amin1, float
command calls sd_channel_control3
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq