search – SWAT+
search Subroutine
38 statements
Source File
subroutine search(sch, max, cfind, iseq)
Arguments
Type Intent Optional Attributes Name
character(len=50), dimension(max) :: sch
integer :: max
character(len=50) :: cfind
integer :: iseq
Called by
Contents
None
Call graph
cli_staread calls search
hyd_read_connect calls search
proc_read calls cli_staread
hyd_connect calls hyd_read_connect
main calls proc_read, hyd_connect