soil_phys_init – SWAT+
soil_phys_init Subroutine
128 statements
Source File
subroutine soil_phys_init(isol)
Uses
soil_module
basin_module
time_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine initializes soil physical properties
~ ~ ~ INCOMING VARIABLES ~ ~ ~
name          |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
ddrain(:)     |mm            |depth to the sub-surface drain
i             |none          |HRU number
rock(:)       |%             |percent of rock fragments in soil layer
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~
name          |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
rock(:)       |none          |exponential value that is a function of
                             |percent rock
sol_st(:,:)   |mm H2O        |amount of water stored in the soil layer
                             |on any given day (less wp water)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~
Intrinsic: Exp, Sqrt
SWAT: Curno
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
Defaults for ph and calcium mjw average of 20,000 SSURGO soils mjw rev 490 calculate water content of soil at -1.5 MPa and -0.033 MPa compute drainable porosity and variable water table factor - Daniel determine detached sediment size distribution typical for mid-western soils in USA (Foster et al., 1980) Based on SWRRB Sand fraction Silt fraction Clay fraction
Small aggregate fraction
Large Aggregate fraction
Error check. May happen for soils with more sand
Soil not typical of mid-western USA
The fraction wont add upto 1.0
initialize water/drainage coefs for each soil layer
initialize water table depth and soil water for Daniel calculate infiltration parameters for subdaily time step
Arguments
Type Intent Optional Attributes Name
integer :: isol
Called by
Contents
None
Call graph
soils_init calls soil_phys_init
proc_hru calls soils_init
main calls proc_hru