soil_awc_init – SWAT+
soil_awc_init Subroutine
65 statements
Source File
subroutine soil_awc_init(isol)
Uses
soil_module
basin_module
time_module
~ ~ ~ PURPOSE ~ ~ ~ this subroutine initializes soil parameters based on awc
~ ~ ~ INCOMING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ddrain(:) |mm |depth to the sub-surface drain i |none |HRU number rock(:) |% |percent of rock fragments in soil layer ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ rock(:) |none |exponential value that is a function of |percent rock sol_st(:,:) |mm H2O |amount of water stored in the soil layer |on any given day (less wp water) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~ Intrinsic: Exp, Sqrt SWAT: Curno
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
calculate water content of soil at -1.5 MPa and -0.033 MPa compute drainable porosity and variable water table factor - Daniel initialize water/drainage coefs for each soil layer initialize water table depth and soil water for Daniel
Arguments
Type Intent Optional Attributes Name
integer :: isol
Called by
Contents
None
Call graph
cal_parm_select calls soil_awc_init
cal_conditions calls cal_parm_select
proc_cal calls cal_conditions
main calls proc_cal