soils_init – SWAT+
soils_init Subroutine
169 statements
Source File
subroutine soils_init()
Uses
basin_module
maximum_data_module
soil_data_module
constituent_mass_module
soil_module
septic_data_module
plant_module
hydrograph_module
organic_mineral_mass_module
time_module
hru_module
set first 10 mm layer set remaining layers 1st layer < 20 mm so dont add 10 mm layer initialize soil physical parameters Section 2 this section sets hru soils to appropriate soil database
allocate soil layers set hru soils to appropriate database soil layers create a biozone layer in septic HRUs allocate soil1 arrays - carbon/nutrients
Arguments
None
Calls
Called by
Contents
None
Call graph
soils_init calls soil_phys_init, layersplit
proc_hru calls soils_init
main calls proc_hru