sq_greenampt – SWAT+
sq_greenampt Subroutine
117 statements
Source File
subroutine sq_greenampt()
Uses
basin_module
soil_module
urban_data_module
climate_module
hydrograph_module
time_module
hru_module
~ ~ ~ PURPOSE ~ ~ ~
Predicts daily runoff given breakpoint precipitation and snow melt
using the Green & Ampt technique
~ ~ ~ INCOMING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
wst(:)%weat%ts(:)  |mm H2O        |precipitation for the time step during day
swtrg(:)    |none          |rainfall event flag:
                           |  0: no rainfall event over midnight
                           |  1: rainfall event over midnight
wfsh(:)     |mm            |average capillary suction at wetting front
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
hhqday(:)   |mm H2O        |surface runoff generated each hour of day
                           |in HRU
surfq(:)    |mm H2O        |surface runoff for the day in HRU
swtrg(:)    |none          |rainfall event flag:
                           |  0: no rainfall event over midnight
                           |  1: rainfall event over midnight
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~
Intrinsic: Sum, Exp, Real, Mod
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
reset values for day calculate effective hydraulic conductivity calculate total amount of rainfall during day for time step and rainfall intensity for time step urban 60./idt NK Feb 4,08
if rainfall intensity is less than infiltration rate everything will infiltrate if rainfall intensity is greater than infiltration rate find cumulative infiltration for time step by successive substitution urban 60./idt NK Feb 4,08 Urban Impervious cover effective pcp is > 0.017 mm/min (or 4/100 inches/hr) the potential for initial dabstraction from paved surface is less than the user input initial dabstraction the potential for initial dabstraction from paved surface increases based on evaporation daily total runoff calculate new rate of infiltration
Arguments
None
Called by
Contents
None
Call graph
sq_volq calls sq_greenampt
surface calls sq_volq
hru_control calls surface
command calls hru_control
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq