structure_set_parms – SWAT+
structure_set_parms Subroutine
77 statements
Source File
subroutine structure_set_parms(str_name, istr, j)
Uses
soil_module
mgt_operations_module
hru_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine controls the simulation of the land phase of the
hydrologic cycle
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
define soil layer the drainage tile is in setting tile lage time Set some defaults if needed minimum value for vfsratio is 0 max is 300 minimum value for vfscon is 0.1 default is 0.5 max is 0.95 minimum value for vfsch is 0 max is .95 Set defaults - Mannings via Fiener, 2006 length based on one side of a square HRU default to a workable depth based on with and 8:1 sideslopes Default to 3/4 HRU slope default sed coeff to 0.005 Calculate time of concentration for waterway similar to hydro_init.f Check the channel to make sure the enter width and depth will work with 8:1 trap channel, assume width is correct Depth and Width not possible with 8:1 sideslope and trapazoidal channel assume b =.25*width Sediment Particulate P Soluble P Particulate N Soluble N Bacteria
Arguments
Type Intent Optional Attributes Name
character(len=16), intent(in) :: str_name
integer, intent(in) :: istr
integer, intent(in) :: j
Calls
Called by
Contents
None
Call graph
structure_set_parms calls ttcoef_wway
actions calls structure_set_parms
proc_hru calls structure_set_parms, structure_init
structure_init calls structure_set_parms
mallo_control calls actions
wallo_demand calls actions
sd_channel_control2 calls actions
main calls proc_hru, time_control, calhard_control, command, calsoft_control
sd_channel_control3 calls actions, wallo_control
time_control calls actions, mallo_control, wallo_control, command
hru_control calls actions
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
wallo_control calls wallo_demand
command calls sd_channel_control2, sd_channel_control3, hru_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq