time_control – SWAT+
time_control Subroutine
266 statements
Source File
subroutine time_control()
Uses
basin_module
maximum_data_module
calibration_data_module
output_landscape_module
output_ls_pesticide_module
constituent_mass_module
water_allocation_module
water_body_module
plant_module
climate_module
sd_channel_module
plant_data_module
conditional_module
hru_lte_module
hydrograph_module
time_module
hru_module
mgt_operations_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine contains the loops governing the modeling of processes
in the watershed
~ ~ ~ INCOMING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
biomix(:)   |none          |biological mixing efficiency.
                           |Mixing of soil due to activity of earthworms
                           |and other soil biota. Mixing is performed at
                           |the end of every calendar year.
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
ic          |none          |counter
iix         |none          |sequence number of current year in rotation
iiz         |none          |sequence number of current crop grown
                           |within the current year
xx          |none          |current year in simulation sequence
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~
Intrinsic: Mod, Real
SWAT: std3, xmon, sim_initday, clicon, command
SWAT: writed, writem, tillmix
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
generate precip for the first day - %precip_next !!! uncomment next three lines for RELEASE version only (Srin/Karim)
determine beginning and ending dates of simulation in current year set beginning day of simulation for year set ending day of simulation for year sum years of printing for average annual writes tell user they are skipping more years than simulating set initial soil water for hru, basin and lsu - for checking water balance won't reset again begin daily loop determine month and day of month - time%mo and time%day_mo Uncomment next three lines for DEBUG version only
check for end of month, year and simulation check time interval for daily printing initialize variables at beginning of day for hru's read in/generate weather
set array counter for atmospheric deposition
conditional reset of land use and management all hru fractions are set at once have to check every hru for land use change allocate water for water rights objects if a channel is not an object, call at beginning of day allocate manure to appropriate demand objects command loop
end daily loop
perform end-of-year processes
write annual basin crop yields and harvested areas zero yearly balances after using them in soft data calibration (was in hru_lte_output) zero yearly balances after using them in soft data calibration (was in sd_channel_output) zero yearly balances after using them in soft data calibration (was in hru_output) zero yearly pesticide balances after using them in soft data calibration (was in hru_output) compute biological mixing at the end of every year update sequence number for year in rotation to that of the next year and reset sequence numbers for operations update simulation year end annual loop
write channel morphology - downcutting and widening ave annual calibration output and reset time for next simulation
Arguments
None
Calls
Called by
Contents
None
Call graph
time_control calls xmon, climate_control, basin_sw_init, amin0, aqu_pest_output_init, conditions, actions, mallo_control, calsoft_sum_output, mgt_newtillmix, cli_precip_control, float, sim_initday, cli_atmodep_time_control, wallo_control, command, calsoft_ave_output
climate_control calls cli_precip_control, cli_weatgn, cli_clgen, cli_wndgen, cli_slrgen, cli_rhgen, cli_bounds_check, cli_tgen
conditions calls float, cond_real, cond_integer
actions calls mgt_newtillmix, amax1, structure_set_parms, mgt_killop, mgt_transplant, pl_burnop, pest_apply, mgt_harvbiomass, pl_graze, mgt_newtillmix_wet, wet_initial, hru_fr_change, amin1, mgt_harvgrain, hru_lum_init, mgt_harvresidue, pl_fert_wet, plant_init, mgt_harvtuber, cn2_init, pl_fert, curno
mallo_control calls conditions, actions, pl_fert
mgt_newtillmix calls mgt_tillfactor
cli_precip_control calls cli_pgen, cli_pgenhr, cli_bounds_check
wallo_control calls wallo_transfer, wallo_demand, wallo_withdraw, salt_irrig, cs_irrig, wallo_treatment
command calls aquifer_output, wetland_output, res_cs_output, flow_dur_curve, basin_chanbud_output, aqu_salt_output, wet_cs_output, recall_output, constit_hyd_mult, hydout_output, basin_recall_output, channel_output, res_salt_output, 1000, res_control, hydin_output, ru_control, obj_output, basin_sdchannel_output, salt_balance, aqu_pesticide_output, sd_chanmorph_output, basin_ch_pest_output, water_allocation_output, recall_cs, cs_balance, sd_channel_control2, sd_chanbud_output, ch_salt_output, basin_res_pest_output, manure_source_output, ru_output, hru_output, sd_channel_output, lsu_output, recall_salt, basin_ls_pest_output, ru_salt_output, gwflow_simulate, sd_channel_control3, manure_demand_output, aqu_cs_output, cha_pesticide_output, basin_aqu_pest_output, aqu_1d_control, hru_lte_output, wet_salt_output, hru_control, ch_cs_output, hru_salt_output, basin_output, hyddep_output, recall_nut, hru_pesticide_output, hru_lte_control, cs_str_output, basin_reservoir_output, basin_aquifer_output, ru_cs_output, hru_pathogen_output, reservoir_output, hru_carbon_output, soil_nutcarb_write, basin_channel_output, hru_cs_output, res_pesticide_output, sd_channel_control, basin_chanmorph_output
aquifer_output calls float
wetland_output calls float
res_cs_output calls float
structure_set_parms calls ttcoef_wway
flow_dur_curve calls float, amin1
aqu_salt_output calls float
mgt_killop calls hpc_d, pl_rootfr, hrc_d
wet_cs_output calls float
mgt_transplant calls float, pl_root_gro, pl_seed_gro, pl_partition
res_salt_output calls float
cli_wndgen calls float
res_control calls conditions, cli_lapse, res_hydro, res_sediment, res_nutrient, res_rel_conds, res_pest, res_salt, res_cs
wallo_demand calls conditions, actions
basin_sdchannel_output calls float
salt_balance calls float
pl_burnop calls curno, hpc_d, hrc_d
aqu_pesticide_output calls float
sd_chanmorph_output calls float
basin_ch_pest_output calls float
mgt_harvbiomass calls hpc_d, hrc_d
wallo_withdraw calls gwflow_ppag
cs_balance calls float
sd_channel_control2 calls conditions, actions, sd_channel_sediment, hyd_convert_conc_to_mass, hyd_convert_mass_to_conc, ch_rtpath, ch_watqual4, ch_rtmusk, ch_rtpest
pl_graze calls amin1
ch_salt_output calls float
basin_res_pest_output calls float
hru_output calls float
sd_channel_output calls float
lsu_output calls float
basin_ls_pest_output calls float
wet_initial calls res_convert_mass
gwflow_simulate calls 1000, 10000, gwflow_chem, 50, gwflow_canl_out, gwflow_rech, gwflow_gwet, gwflow_ppex
sd_channel_control3 calls conditions, actions, wallo_control, cli_lapse, ch_rtpath, gwflow_gwsw, gwflow_canl, gwflow_tile, gwflow_satx, ch_rtmusk, sd_channel_sediment3, ch_rtpest
aqu_cs_output calls float
cha_pesticide_output calls float
basin_aqu_pest_output calls float
aqu_1d_control calls amin1, salt_chem_aqu, cs_rctn_aqu, cs_sorb_aqu
hru_lte_output calls float
wet_salt_output calls float
hru_control calls conditions, actions, pl_graze, pl_fert, cbn_zhang2, cs_rctn_hru, sq_canopyint, nut_nrain, pest_decay, hru_urb_bmp, wet_irrp, cs_rain, nut_nitvol, nut_nlch, hpc_d, salt_roadsalt, sq_surfst, hru_hyds, sep_biozone, swr_latsed, cs_sorb_hru, nut_orgn, nut_solp, varinit, swr_percmain, pl_grow, pl_community, path_ls_swrouting, salt_lch, rls_routetile, pest_washp, hsc_d, nut_pminrl2, stmp_solt, swr_subwq, path_ls_runoff, salt_rain, hru_urbanhr, pest_pl_up, swr_substor, hscf_d, sq_snom, path_ls_process, nut_nminrl, nut_pminrl, pest_lch, rls_routesurf, hru_urban, nut_orgnc, pest_soil_tot, stor_surfstor, smp_filter, sq_crackvol, surface, wetland_control, hrc_d, pest_enrsb, et_pot, smp_buffer, rls_routesoil, albedo, pest_pesty, nut_psed, et_act, smp_grass_wway, salt_chem_hru, rls_routeaqu, nut_orgnc2, mgt_operatn, cs_lch, smp_bmpfixed
ch_cs_output calls float
hru_salt_output calls float
basin_output calls float
mgt_harvgrain calls hpc_d
hru_pesticide_output calls float
basin_reservoir_output calls float
basin_aquifer_output calls float
hru_pathogen_output calls float
reservoir_output calls float
hru_carbon_output calls hrc_a, hpc_d, hpc_m, hpc_y, hsc_d, hpc_a, hsc_m, hscf_d, hsc_y, hscf_m, hsc_a, hscf_y, hrc_d, hscf_a, hrc_m, hrc_y
plant_init calls xmon, float, amin1, pl_root_gro, pl_seed_gro, pl_partition
mgt_harvtuber calls pl_rootfr
wallo_treatment calls hyd_convert_conc_to_mass
hru_cs_output calls float
res_pesticide_output calls float
cn2_init calls curno
basin_chanmorph_output calls float
cs_rctn_hru calls se_reactions_soil
nut_nrain calls float
cs_rain calls float
ch_rtpath calls theta
salt_roadsalt calls float
hru_hyds calls float, min1, flow_hyd_ru_hru
ch_watqual4 calls amin1
swr_percmain calls amin1, swr_drains, swr_percmicro, swr_satexcess, gwflow_soil, swr_origtile, swr_percmacro
pl_grow calls pl_root_gro, pl_seed_gro, pl_partition, pl_dormant, pl_biomass_gro, pl_mortality, pl_leaf_senes, pl_leaf_gro, pl_nut_demand
pl_community calls pl_waterup
salt_chem_aqu calls nacl, activity_coefficient, caso4, caco3, cationexchange, mgso4, ionic_strength, mgco3
res_nutrient calls amin1
nut_pminrl2 calls alog
cs_rctn_aqu calls se_reactions_aquifer
swr_subwq calls hsc_d
pl_root_gro calls float, amin1
salt_rain calls float
hru_urbanhr calls hru_sweep
ch_rtmusk calls rcurv_interp_flo
res_rel_conds calls cond_real_c, cond_integer_c
sd_channel_sediment3 calls amax1, rcurv_interp_flo
res_pest calls amin1
surface calls ero_ysed, sq_volq, ero_eiusle, sq_dailycn, ero_pkq, sq_crackflow, ero_ovrsed, ero_cfactor
wetland_control calls conditions, res_hydro, res_sediment, res_nutrient, wet_cs, gwflow_wetl, wet_salt, ero_cfactor
nut_psed calls amin1
et_act calls amin1
salt_chem_hru calls 50, nacl, activity_coefficient, caso4, caco3, cationexchange, mgso4, ionic_strength, mgco3
nut_orgnc2 calls hsc_d
mgt_operatn calls mgt_sched
swr_drains calls swr_depstor
rcurv_interp_flo calls chrc_interp
pl_dormant calls amin1
sq_volq calls sq_daycn, sq_greenampt
pl_biomass_gro calls hpc_d, pl_tstr, pl_pup, pl_nup, cs_uptake, salt_uptake
pl_mortality calls amin1
swr_satexcess calls amin1
pl_leaf_senes calls amin1, hpc_d, hrc_d
pl_leaf_gro calls float, amin1, alog10
mgt_sched calls mgt_newtillmix, mgt_killop, mgt_transplant, pl_burnop, pest_apply, mgt_harvbiomass, mgt_newtillmix_wet, mgt_harvgrain, mgt_harvresidue, pl_fert_wet, mgt_harvtuber, pl_fert, curno, salt_fert_wet, cs_fert_wet, salt_fert, mgt_plantop, cs_fert
pl_nut_demand calls pl_nupd, pl_pupd
pl_waterup calls amin1, salt_chem_soil_single
pl_tstr calls amin1
pl_pup calls nuts
pl_nupd calls float
salt_chem_soil_single calls nacl, activity_coefficient, caso4, caco3, mgso4, ionic_strength, mgco3
pl_nup calls amin1, nuts, pl_nfix
pl_pupd calls float
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, calsoft_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq