topohyd_init – SWAT+
topohyd_init Subroutine
75 statements
Source File
subroutine topohyd_init()
Uses
soil_data_module
hydrology_data_module
plant_module
topography_data_module
hydrograph_module
hru_module
set hru snow paramters shape parameters to describes area of snow cover as a function of amount of snow try setting for tile changing hrg_pet to pet_co - works for old harg_pet input and new pet_co
Arguments
None
Calls
Called by
Contents
None
Call graph
topohyd_init calls ascrv, amin1
proc_hru calls topohyd_init
main calls proc_hru