unit_hyd – SWAT+
unit_hyd Subroutine
62 statements
Source File
subroutine unit_hyd(tc, uh)
Uses
basin_module
time_module
~ ~ ~ PURPOSE ~ ~ ~ This subroutine computes variables related to the watershed hydrology: the time of concentration for the subbasins, lagged surface runoff, the coefficient for the peak runoff rate equation, and lateral flow travel time.
~ ~ ~ INCOMING VARIABLES ~ ~ ~1 name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ch_n(1,:) |none |Manning"s "n" value for the tributary channels ch_s(1,:) |m/m |average slope of tributary channels gdrain(:) |hrs |drain tile lag time: the amount of time |between the transfer of water from the soil |to the drain tile and the release of the |water from the drain tile to the reach. hru_km(:) |km2 |area of HRU in square kilometers lat_ttime(:)|days |lateral flow travel time slsoil(:) |m |slope length for lateral subsurface flow slsubbsn(:) |m |average slope length for subbasin tconc(:) |hr |time of concentration ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ lat_ttime(:)|none |Exponential of the lateral flow travel time ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ l |none |counter scmx |mm/hr |maximum soil hydraulic conductivity t_ch |hr |time for flow entering the farthest upstream |channel to reach the subbasin outlet xx |none |variable to hold calculation result ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~
SWAT: Ttcoef
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
sum 20 points on the unit hydrograph to get sum for the time%step
increment within the time step to get accurate estimates near peak Triangular Unit Hydrograph rising limb of hydrograph falling limb of hydrograph Gamma Function Unit Hydrograph
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: tc
real, intent(out), dimension(bsn_prm%day_lag_mx,time%step) :: uh
compute unit hydrograph for computing hydrograph from direct runoff
Calls
Called by
Contents
None
Call graph
unit_hyd calls float
unit_hyd_ru_hru calls unit_hyd
main calls unit_hyd_ru_hru