wallo_treatment – SWAT+
wallo_treatment Subroutine
28 statements
Source File
subroutine wallo_treatment(iwallo, idmd)
Uses
hydrograph_module
water_allocation_module
treated outflow is a fraction of withdrawal convert concentration to mass recall option for treated water
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iwallo
integer, intent(in) :: idmd
Calls
Called by
Contents
None
Call graph
wallo_treatment calls hyd_convert_conc_to_mass
wallo_control calls wallo_treatment
sd_channel_control3 calls wallo_control
time_control calls wallo_control, command
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, command, calsoft_control
command calls sd_channel_control3
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq