wallo_control – SWAT+
wallo_control Subroutine
105 statements
Source File
subroutine wallo_control(iwallo)
Uses
basin_module
water_allocation_module
constituent_mass_module
soil_module
plant_module
hydrograph_module
time_module
organic_mineral_mass_module
hru_module
check if canal or inflow diversions and set available water from recall object set total volumes of canal diversions (source = "div") - rtb set total volumes of inflow diversions from recall file set total volumes of inflow diversions from monthly flow rate (m3/s) loop through each demand object zero demand, withdrawal, and unmet for each source set demand for each object if demand - check source availability check if water is available from each source - set withdrawal and unmet loop through sources again to check if compensation is allowed compute total withdrawal for demand object from all sources if irrigating set amount applied and runoff irrigation demand treatment of withdrawn water no treatment - treated = withdrawal compute treatment by inputting the mass or concentrations transfer (diversion) of withdrawn and possibly treated water sum demand, withdrawal, and unmet for entire allocation object
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: iwallo
Calls
Called by
Contents
None
Call graph
wallo_control calls wallo_demand, salt_irrig, wallo_transfer, cs_irrig, wallo_withdraw, wallo_treatment
wallo_demand calls conditions, actions
wallo_withdraw calls gwflow_ppag
wallo_treatment calls hyd_convert_conc_to_mass
conditions calls cond_real, cond_integer, float
actions calls mgt_newtillmix_wet, amax1, wet_initial, hru_lum_init, pl_burnop, mgt_newtillmix, mgt_harvresidue, pest_apply, structure_set_parms, mgt_harvbiomass, hru_fr_change, pl_fert_wet, mgt_killop, plant_init, amin1, mgt_transplant, mgt_harvtuber, pl_graze, cn2_init, pl_fert, mgt_harvgrain, curno
wet_initial calls res_convert_mass
pl_burnop calls curno, hpc_d, hrc_d
mgt_newtillmix calls mgt_tillfactor
structure_set_parms calls ttcoef_wway
mgt_harvbiomass calls hpc_d, hrc_d
mgt_killop calls hpc_d, hrc_d, pl_rootfr
plant_init calls amin1, float, xmon, pl_partition, pl_root_gro, pl_seed_gro
mgt_transplant calls float, pl_partition, pl_root_gro, pl_seed_gro
mgt_harvtuber calls pl_rootfr
pl_graze calls amin1
cn2_init calls curno
mgt_harvgrain calls hpc_d
pl_root_gro calls amin1, float
sd_channel_control3 calls wallo_control
time_control calls wallo_control, command
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, command, calsoft_control
command calls sd_channel_control3
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq