wallo_demand – SWAT+
wallo_demand Subroutine
67 statements
Source File
subroutine wallo_demand(iwallo, idmd)
Uses
water_allocation_module
conditional_module
hydrograph_module
hru_module
reservoir_module
compute total demand from each demand object minicipal demand use recall object for demand reservoir demand use average daily or a flow control decision table use decision table for flow control - water allocation diversion demand use average daily or a flow control decision table use decision table for flow control - water allocation irrigation demand if there is demand, use amount from water allocation file initialize unmet to total demand and subtract as water is withdrawn compute demand from each source object
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iwallo
integer, intent(in) :: idmd
Calls
Called by
Contents
None
Call graph
wallo_demand calls conditions, actions
conditions calls cond_real, cond_integer, float
actions calls mgt_newtillmix_wet, amax1, wet_initial, hru_lum_init, pl_burnop, mgt_newtillmix, mgt_harvresidue, pest_apply, structure_set_parms, mgt_harvbiomass, hru_fr_change, pl_fert_wet, mgt_killop, plant_init, amin1, mgt_transplant, mgt_harvtuber, pl_graze, cn2_init, pl_fert, mgt_harvgrain, curno
wet_initial calls res_convert_mass
pl_burnop calls curno, hpc_d, hrc_d
mgt_newtillmix calls mgt_tillfactor
structure_set_parms calls ttcoef_wway
mgt_harvbiomass calls hpc_d, hrc_d
mgt_killop calls hpc_d, hrc_d, pl_rootfr
plant_init calls amin1, float, xmon, pl_partition, pl_root_gro, pl_seed_gro
mgt_transplant calls float, pl_partition, pl_root_gro, pl_seed_gro
mgt_harvtuber calls pl_rootfr
pl_graze calls amin1
cn2_init calls curno
mgt_harvgrain calls hpc_d
pl_root_gro calls amin1, float
wallo_control calls wallo_demand
sd_channel_control3 calls wallo_control
time_control calls wallo_control, command
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, command, calsoft_control
command calls sd_channel_control3
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq