wallo_withdraw – SWAT+
wallo_withdraw Subroutine
114 statements
Source File
subroutine wallo_withdraw(iwallo, idmd, isrc)
Uses
basin_module
water_allocation_module
hydrograph_module
time_module
reservoir_module
aquifer_module
check if water is available from each source - set withdrawal and unmet divert flowing water from channel source amount that can be diverted without falling below low flow limit reservoir source diversion inflow source aquifer source only have flow, no3, and minp(solp) for aquifer canal diversion source (water removed from channel using point source) unlimited source add source withdrawal hyd to get total withdrawal hyd for the demand object subtract withdrawal from unmet
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iwallo
integer, intent(in) :: idmd
integer, intent(in) :: isrc
Calls
Called by
Contents
None
Call graph
wallo_withdraw calls gwflow_ppag
wallo_control calls wallo_withdraw
sd_channel_control3 calls wallo_control
time_control calls wallo_control, command
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, calhard_control, command, calsoft_control
command calls sd_channel_control3
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq