wet_all_initial – SWAT+
wet_all_initial Subroutine
15 statements
Source File
subroutine wet_all_initial()
Uses
hydrograph_module
hru_module
set initial volumes and convert units
Arguments
None
Calls
Called by
Contents
None
Call graph
wet_all_initial calls wet_initial
wet_initial calls res_convert_mass
main calls wet_all_initial