wet_initial – SWAT+
wet_initial Subroutine
98 statements
Source File
subroutine wet_initial(iihru)
Uses
maximum_data_module
constituent_mass_module
soil_module
water_body_module
res_cs_module
hydrograph_module
hru_module
reservoir_module
reservoir_data_module
res_salt_module
hamm10. => m**3 - assume entire hru is wet and don't use fractional inputs (for simplicity) set initial weir height to principal depth - m set initial n and p concentrations --> (ppm) * (m^3) / 1000 = kg !! ppm = t/m^3 * 10^6 set initial salt ion concentrations and mass (rtb salt) set initial constituent concentrations and mass (rtb cs) update surface area wetland on hru - solve quadratic to find new depth
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iihru
Calls
Called by
Contents
None
Call graph
wet_initial calls res_convert_mass
actions calls wet_initial
wet_all_initial calls wet_initial
mallo_control calls actions
wallo_demand calls actions
sd_channel_control2 calls actions
main calls wet_all_initial, time_control, calhard_control, command, calsoft_control
sd_channel_control3 calls actions, wallo_control
time_control calls actions, mallo_control, wallo_control, command
hru_control calls actions
caltsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
wallo_control calls wallo_demand
command calls sd_channel_control2, sd_channel_control3, hru_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls caltsoft_hyd, calsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq