wetland_control – SWAT+
wetland_control Subroutine
176 statements
Source File
subroutine wetland_control()
Uses
channel_module
basin_module
constituent_mass_module
soil_module
water_body_module
conditional_module
climate_module
hydrograph_module
time_module
organic_mineral_mass_module
aquifer_module
hru_module
reservoir_module
gwflow_module
reservoir_data_module
mgt_operations_module
zero outgoing flow set water body pointer to res initialize variables for wetland daily simulation add precipitation - mmha10.=m3 (used same area for infiltration and soil evap) add irrigation water to the paddy/wetland storage update wetland surface area - solve quadratic to find new depth infiltration of the standing water to the topsoil layer. Any excess infiltration volume estimated here is reverted (back to waterbody) in swr_satexcess. if not a floodplain wetland
calc release from decision table weir discharge (ht2) by decision tables subtract outflow from storage daily total runoff compute sediment deposition ! subtract sediment leaving from reservoir
perform reservoir nutrient balance perform salt ion constituent balance perform wetland constituent balance perform reservoir pesticide transformations
set values for routing variables undefined
set inflow and outflow variables for reservoir_output
Arguments
None
Calls
Called by
Contents
None
Call graph
wetland_control calls gwflow_wetl, res_sediment, wet_salt, conditions, res_hydro, res_nutrient, wet_cs, ero_cfactor
conditions calls cond_real, float, cond_integer
res_nutrient calls amin1
hru_control calls wetland_control
command calls hru_control
time_control calls command
main calls command, time_control, calhard_control, calsoft_control
calsoft_hyd calls time_control
calsoft_plant calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_perc calls time_control
caltsoft_hyd calls time_control
calhard_control calls time_control
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
calsoft_control calls calsoft_hyd, calsoft_plant, caltsoft_hyd, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq