xmon – SWAT+
xmon Subroutine
20 statements
Source File
subroutine xmon(jd, mo, day_mo)
Uses
time_module
~ ~ ~ PURPOSE ~ ~ ~ this subroutine determines the month, given the julian date and leap year flag
~ ~ ~ INCOMING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ndays(:) |julian date |julian date for last day of preceding |month (where the array location is the |number of the month). The dates are for |leap years ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: jd
integer, intent(out) :: mo
integer, intent(out) :: day_mo
Called by
Contents
None
Call graph
plant_init calls xmon
time_read calls xmon
cli_tmeas calls xmon
time_control calls xmon, actions, mallo_control, wallo_control, command
actions calls plant_init
plant_all_init calls plant_init
calsoft_hyd calls time_control
proc_bsn calls time_read
calsoft_hyd_bfr_et calls time_control
caltsoft_hyd calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_plant calls time_control
calhard_control calls time_control
main calls time_control, proc_bsn, calhard_control, proc_date_time, calsoft_control, proc_hru, command
proc_date_time calls cli_tmeas
calsoft_chsed calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_sed calls time_control
mallo_control calls actions
wallo_demand calls actions
sd_channel_control2 calls actions
calsoft_control calls calsoft_hyd, caltsoft_hyd, calsoft_plant, calsoft_chsed, calsoft_sed, calsoft_hyd_bfr
sd_channel_control3 calls actions, wallo_control
hru_control calls actions
proc_hru calls plant_all_init
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_surq, calsoft_hyd_bfr_latq
wallo_control calls wallo_demand
command calls sd_channel_control2, sd_channel_control3, hru_control