main – SWAT+
main Program
79 statements
Source File
Uses
hydrograph_module
time_module
maximum_data_module
calibration_data_module
!! for Luis only
!! for Luis only
read decision table data for conditional management simulate watershed processes export coefficient - average annual write output for SWIFT input write successful completion to screen and file
Calls
Contents
Variables
date_time b
Variables
Type Attributes Name Initial
integer :: date_time(8)
character(len=10) :: b(3)
Call graph
main calls hyd_connect, proc_cha, wet_read, proc_aqu, dr_db_read, proc_hru, hru_lte_read, wet_all_initial, wet_fp_init, swift_output, hyd_connect_out, dr_ru, unit_hyd_ru_hru, proc_bsn, proc_db, exco_db_read, dtbl_res_read, om_water_init, res_read_weir, cal_cond_read, cli_lapse, dtbl_flocon_read, time_control, proc_read, salt_cha_read, proc_res, wet_read_salt_cs, cal_parmchg_read, manure_allocation_read, lsu_read_elements, proc_cond, dtbl_scen_read, wet_read_hyd, proc_open, calhard_control, path_cha_res_read, hru_dtbl_actions_init, proc_cal, treat_read_om, proc_date_time, object_read_output, pest_cha_res_read, cs_cha_read, dtbl_lum_read, command, calsoft_control, water_allocation_read
hyd_connect calls dr_db_read, overbank_read, recall_read_salt, gwflow_chan_read, recall_read_cs, ru_read_elements, aqu2d_read, hyd_read_connect, gwflow_read, recall_read, ru_read
proc_cha calls overbank_read, ch_initial, sd_channel_surf_link, ch_read_init, ch_read_init_cs, ch_read_nut, sd_hydsed_read, ch_read_hyd, ch_read_sed, ch_read, sd_channel_read, time_conc_init, sd_hydsed_init, aqu2d_init, ch_ttcoef
proc_aqu calls aqu_read_init_cs, aqu_initial, aqu_read, aqu_read_init
dr_db_read calls dr_path_read, dr_read_hmet, dr_read_salt, dr_read_om, dr_read_pest
proc_hru calls hru_output_allo, hru_lum_init_all, structure_set_parms, plant_all_init, cn2_init_all, hydro_init, pathogen_init, salt_hru_init, hru_allo, topohyd_init, cs_hru_init, hru_read, carbon_read, rte_read_nut, soils_init, structure_init, hrudb_init, pesticide_init
hru_lte_read calls amin1, ascrv
wet_all_initial calls wet_initial
swift_output calls hyd_convert_mass_to_conc
dr_ru calls amin1
unit_hyd_ru_hru calls unit_hyd
proc_bsn calls basin_read_objs, basin_prm_default, basin_read_cc, time_read, basin_print_codes_read, basin_read_prm, co2_read, readcio_read
proc_db calls mgt_read_mgtops, till_parm_read, cons_prac_read, mgt_read_harvops, mgt_read_puddle, plant_parm_read, scen_read_grwway, sep_read, scen_read_bmpuser, readpcom, fert_parm_read, septic_parm_read, plantparm_init, sdr_read, overland_n_read, plant_transplant_read, landuse_read, mgt_read_irrops, scen_read_filtstrip, pest_parm_read, mgt_read_grazeops, mgt_read_chemapp, cntbl_read, path_parm_read, mgt_read_sweepops, urban_parm_read, mgt_read_fireops
exco_db_read calls exco_read_salt, exco_read_om, exco_read_pest, exco_read_path, exco_read_hmet
time_control calls command, climate_control, mgt_newtillmix, cli_atmodep_time_control, basin_sw_init, actions, mallo_control, xmon, cli_precip_control, calsoft_sum_output, amin0, calsoft_ave_output, wallo_control, aqu_pest_output_init, conditions, sim_initday, float
proc_read calls pest_hru_aqu_read, cs_uptake_read, salt_irr_read, salt_hru_read, field_read, salt_aqu_read, hmet_hru_aqu_read, cli_read_atmodep_salt, cli_read_atmodep_cs, snowdb_read, ch_read_temp, cs_irr_read, soil_plant_init_cs, hydrol_read, cli_read_atmodep, salt_uptake_read, salt_fert_read, cs_fert_read, soil_plant_init, path_hru_aqu_read, cs_reactions_read, cs_urban_read, cs_aqu_read, cli_staread, constit_db_read, topo_read, salt_urban_read, cs_plant_read, salt_roadsalt_read, solt_db_read, salt_plant_read, soil_lte_db_read, cs_hru_read, soil_db_read, pest_metabolite_read
proc_res calls res_read_hyd, res_read_sed, res_read_nut, res_read_init, res_read_saltdb, res_read_csdb, res_allo, res_objects, res_read_salt_cs, res_read_conds, res_initial, res_read
cal_parmchg_read calls define_unit_elements
lsu_read_elements calls define_unit_elements
proc_open calls header_sd_channel, header_water_allocation, header_pest, header_aquifer, header_path, header_reservoir, header_mgt, header_salt, header_lu_change, header_yield, header_const, header_write, header_hyd, header_channel, header_wetland, header_snutc, output_landscape_init
calhard_control calls time_control, re_initialize
proc_cal calls cal_parmchg_read, cal_parm_read, ch_read_orders_cal, calsoft_read_codes, ch_read_parms_cal, cal_allo_init, lcu_read_softcal, ls_read_lsparms_cal, pl_read_parms_cal, aqu_read_elements, ch_read_elements, res_read_elements, pl_read_regions_cal, rec_read_elements, cal_conditions
proc_date_time calls cli_pmeas, cli_hmeas, cli_wmeas, cli_smeas, cli_wgnread, cli_tmeas, cli_petmeas
command calls wetland_output, res_cs_output, aquifer_output, aqu_cs_output, aqu_salt_output, wet_cs_output, recall_output, constit_hyd_mult, hydout_output, basin_recall_output, channel_output, res_salt_output, 1000, res_control, hydin_output, ru_control, obj_output, basin_sdchannel_output, aqu_pesticide_output, sd_chanmorph_output, basin_ch_pest_output, flow_dur_curve, water_allocation_output, recall_cs, cs_balance, sd_channel_control2, sd_chanbud_output, salt_balance, ch_salt_output, basin_res_pest_output, basin_chanbud_output, manure_source_output, ru_output, hru_output, sd_channel_output, lsu_output, recall_salt, ru_salt_output, basin_ls_pest_output, sd_channel_control3, cha_pesticide_output, hru_cs_output, basin_aqu_pest_output, aqu_1d_control, hru_lte_output, wet_salt_output, gwflow_simulate, hru_control, ch_cs_output, hru_salt_output, basin_output, manure_demand_output, hyddep_output, recall_nut, hru_pesticide_output, hru_lte_control, cs_str_output, ru_cs_output, basin_aquifer_output, basin_reservoir_output, hru_pathogen_output, hru_carbon_output, reservoir_output, soil_nutcarb_write, basin_channel_output, res_pesticide_output, sd_channel_control, basin_chanmorph_output
calsoft_control calls calsoft_sed, pl_write_parms_cal, calsoft_chsed, calsoft_hyd, calsoft_hyd_bfr, calsoft_plant, caltsoft_hyd
hru_output_allo calls hrc_a, hpc_d, hpc_m, hpc_y, hsc_d, hpc_a, hsc_m, hscf_d, hsc_y, hscf_m, hsc_a, hscf_y, hrc_d, hscf_a, hrc_m, hrc_y
climate_control calls cli_precip_control, cli_weatgn, cli_clgen, cli_wndgen, cli_slrgen, cli_rhgen, cli_bounds_check, cli_tgen
wetland_output calls float
hru_lum_init_all calls hru_lum_init
res_cs_output calls float
structure_set_parms calls ttcoef_wway
plant_all_init calls plant_init
mgt_read_mgtops calls read_mgtops
mgt_newtillmix calls mgt_tillfactor
aquifer_output calls float
aqu_cs_output calls float
gwflow_chan_read calls 30
aqu_salt_output calls float
wet_cs_output calls float
cn2_init_all calls cn2_init
res_salt_output calls float
res_control calls cli_lapse, conditions, res_hydro, res_sediment, res_nutrient, res_rel_conds, res_pest, res_salt, res_cs
calsoft_sed calls time_control, re_initialize, amin1
basin_sdchannel_output calls float
aqu_pesticide_output calls float
sd_chanmorph_output calls float
actions calls structure_set_parms, mgt_newtillmix, wet_initial, amin1, amax1, mgt_killop, mgt_transplant, pl_burnop, pest_apply, mgt_harvbiomass, pl_graze, mgt_newtillmix_wet, hru_fr_change, mgt_harvgrain, hru_lum_init, mgt_harvresidue, plant_init, pl_fert_wet, mgt_harvtuber, cn2_init, pl_fert, curno
basin_ch_pest_output calls float
pl_write_parms_cal calls amin1
flow_dur_curve calls amin1, float
cs_balance calls float
ru_read_elements calls define_unit_elements
mallo_control calls actions, conditions, pl_fert
sd_channel_control2 calls hyd_convert_mass_to_conc, actions, conditions, sd_channel_sediment, hyd_convert_conc_to_mass, ch_rtpath, ch_watqual4, ch_rtmusk, ch_rtpest
salt_balance calls float
aqu2d_read calls define_unit_elements
ch_salt_output calls float
basin_res_pest_output calls float
hru_output calls float
sd_channel_output calls float
lsu_output calls float
topohyd_init calls amin1, ascrv
unit_hyd calls float
time_read calls xmon
plantparm_init calls ascrv
basin_ls_pest_output calls float
wet_initial calls res_convert_mass
cli_precip_control calls cli_pgen, cli_pgenhr, cli_bounds_check
sd_channel_control3 calls cli_lapse, actions, wallo_control, conditions, ch_rtpath, gwflow_gwsw, gwflow_canl, gwflow_tile, gwflow_satx, ch_rtmusk, sd_channel_sediment3, ch_rtpest
hru_read calls allocate_parms
cli_wgnread calls gcycl, cli_initwgn
cha_pesticide_output calls float
hru_cs_output calls float
pl_read_parms_cal calls define_unit_elements
basin_aqu_pest_output calls float
aqu_read_elements calls define_unit_elements
aqu_1d_control calls amin1, salt_chem_aqu, cs_rctn_aqu, cs_sorb_aqu
hru_lte_output calls float
wet_salt_output calls float
gwflow_simulate calls 1000, 10000, gwflow_chem, 50, gwflow_canl_out, gwflow_rech, gwflow_gwet, gwflow_ppex
hru_control calls actions, conditions, cbn_zhang2, cs_rctn_hru, sq_canopyint, pest_decay, nut_nrain, wet_irrp, hru_urb_bmp, nut_nitvol, cs_rain, hpc_d, nut_nlch, salt_roadsalt, sq_surfst, hru_hyds, sep_biozone, swr_latsed, cs_sorb_hru, nut_orgn, nut_solp, varinit, swr_percmain, pl_grow, pl_community, path_ls_swrouting, rls_routetile, salt_lch, hsc_d, nut_pminrl2, pest_washp, pl_graze, stmp_solt, swr_subwq, path_ls_runoff, salt_rain, hru_urbanhr, pest_pl_up, swr_substor, hscf_d, sq_snom, path_ls_process, nut_nminrl, nut_pminrl, pest_lch, rls_routesurf, nut_orgnc, hru_urban, pest_soil_tot, stor_surfstor, smp_filter, sq_crackvol, surface, wetland_control, hrc_d, pest_enrsb, et_pot, smp_buffer, rls_routesoil, albedo, pest_pesty, et_act, nut_psed, smp_grass_wway, salt_chem_hru, rls_routeaqu, nut_orgnc2, pl_fert, mgt_operatn, cs_lch, smp_bmpfixed
ch_cs_output calls float
calsoft_chsed calls time_control, re_initialize, amin1
hyd_read_connect calls search
soils_init calls soil_phys_init, layersplit
hru_salt_output calls float
basin_output calls float
cli_staread calls search
ch_read_elements calls define_unit_elements
hru_pesticide_output calls float
gwflow_read calls 1000, 10000, 50, 10
calsoft_hyd calls time_control, re_initialize, amin1, curno
structure_init calls structure_set_parms
wallo_control calls wallo_transfer, wallo_demand, wallo_withdraw, salt_irrig, cs_irrig, wallo_treatment
cli_tmeas calls xmon
basin_aquifer_output calls float
basin_reservoir_output calls float
res_initial calls res_convert_mass
res_read_elements calls define_unit_elements
hru_pathogen_output calls float
hru_carbon_output calls hrc_a, hpc_d, hpc_m, hpc_y, hsc_d, hpc_a, hsc_m, hscf_d, hsc_y, hscf_m, hsc_a, hscf_y, hrc_d, hscf_a, hrc_m, hrc_y
reservoir_output calls float
calsoft_hyd_bfr calls calsoft_hyd_bfr_latq, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_et, calsoft_hyd_bfr_surq
conditions calls float, cond_real, cond_integer
pl_read_regions_cal calls define_unit_elements
rec_read_elements calls define_unit_elements
res_pesticide_output calls float
calsoft_plant calls time_control, re_initialize, amin1, calsoft_plant_zero
cal_conditions calls cal_parm_select
basin_chanmorph_output calls float
caltsoft_hyd calls time_control, amin1, ascrv
cs_rctn_hru calls se_reactions_soil
nut_nrain calls float
calsoft_hyd_bfr_latq calls time_control, re_initialize, amin1
cs_rain calls float
mgt_killop calls hpc_d, hrc_d, pl_rootfr
ch_rtpath calls theta
calsoft_hyd_bfr_perc calls time_control, re_initialize, amin1
mgt_transplant calls float, pl_seed_gro, pl_partition, pl_root_gro
salt_roadsalt calls float
hru_hyds calls float, min1, flow_hyd_ru_hru
cal_parm_select calls amin1, curno, soil_awc_init, soil_text_init
cli_wndgen calls float
ch_watqual4 calls amin1
swr_percmain calls amin1, swr_drains, swr_percmicro, swr_satexcess, gwflow_soil, swr_origtile, swr_percmacro
pl_grow calls pl_seed_gro, pl_dormant, pl_biomass_gro, pl_mortality, pl_partition, pl_leaf_senes, pl_leaf_gro, pl_root_gro, pl_nut_demand
wallo_demand calls actions, conditions
pl_burnop calls hpc_d, hrc_d, curno
pl_community calls pl_waterup
salt_chem_aqu calls nacl, activity_coefficient, caso4, caco3, cationexchange, mgso4, ionic_strength, mgco3
res_nutrient calls amin1
mgt_harvbiomass calls hpc_d, hrc_d
wallo_withdraw calls gwflow_ppag
nut_pminrl2 calls alog
pl_graze calls amin1
cs_rctn_aqu calls se_reactions_aquifer
swr_subwq calls hsc_d
salt_rain calls float
hru_urbanhr calls hru_sweep
calsoft_hyd_bfr_et calls time_control, re_initialize, amin1
ch_rtmusk calls rcurv_interp_flo
res_rel_conds calls cond_real_c, cond_integer_c
sd_channel_sediment3 calls amax1, rcurv_interp_flo
res_pest calls amin1
surface calls ero_ysed, sq_volq, ero_eiusle, sq_dailycn, ero_pkq, sq_crackflow, ero_ovrsed, ero_cfactor
wetland_control calls conditions, res_hydro, res_sediment, res_nutrient, wet_cs, gwflow_wetl, wet_salt, ero_cfactor
mgt_harvgrain calls hpc_d
calsoft_hyd_bfr_surq calls time_control, re_initialize, amin1, curno
plant_init calls xmon, amin1, float, pl_seed_gro, pl_partition, pl_root_gro
et_act calls amin1
nut_psed calls amin1
mgt_harvtuber calls pl_rootfr
wallo_treatment calls hyd_convert_conc_to_mass
allocate_parms calls zero2, zero0, zeroini, zero1
salt_chem_hru calls 50, nacl, activity_coefficient, caso4, caco3, cationexchange, mgso4, ionic_strength, mgco3
nut_orgnc2 calls hsc_d
cn2_init calls curno
mgt_operatn calls mgt_sched
swr_drains calls swr_depstor
rcurv_interp_flo calls chrc_interp
pl_dormant calls amin1
sq_volq calls sq_daycn, sq_greenampt
pl_biomass_gro calls hpc_d, pl_tstr, pl_pup, pl_nup, cs_uptake, salt_uptake
pl_mortality calls amin1
swr_satexcess calls amin1
pl_leaf_senes calls amin1, hpc_d, hrc_d
pl_leaf_gro calls amin1, float, alog10
mgt_sched calls mgt_newtillmix, mgt_killop, mgt_transplant, pl_burnop, pest_apply, mgt_harvbiomass, mgt_newtillmix_wet, mgt_harvgrain, mgt_harvresidue, pl_fert_wet, mgt_harvtuber, pl_fert, curno, salt_fert_wet, cs_fert_wet, salt_fert, mgt_plantop, cs_fert
pl_root_gro calls amin1, float
pl_nut_demand calls pl_nupd, pl_pupd
pl_waterup calls amin1, salt_chem_soil_single
pl_tstr calls amin1
pl_pup calls nuts
pl_nupd calls float
salt_chem_soil_single calls nacl, activity_coefficient, caso4, caco3, mgso4, ionic_strength, mgco3
pl_nup calls amin1, nuts, pl_nfix
pl_pupd calls float